package remotecontrol

type RemoteControlEnableParams = EnableParams
type RemoteControlDisableParams = DisableParams
type RemoteControlConnectionStatus = ConnectionStatus
type RemoteControlStatusChangedNotification = StatusChangedNotification
