// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: codex.code_mode.v1.proto

package codemodev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeModeHost_Transport_FullMethodName               = "/codex.code_mode.v1.CodeModeHost/Transport"
	CodeModeHost_OpenSession_FullMethodName             = "/codex.code_mode.v1.CodeModeHost/OpenSession"
	CodeModeHost_CloseSession_FullMethodName            = "/codex.code_mode.v1.CodeModeHost/CloseSession"
	CodeModeHost_SubscribeToToolCalls_FullMethodName    = "/codex.code_mode.v1.CodeModeHost/SubscribeToToolCalls"
	CodeModeHost_CompleteToolCall_FullMethodName        = "/codex.code_mode.v1.CodeModeHost/CompleteToolCall"
	CodeModeHost_AcknowledgeNotification_FullMethodName = "/codex.code_mode.v1.CodeModeHost/AcknowledgeNotification"
	CodeModeHost_Execute_FullMethodName                 = "/codex.code_mode.v1.CodeModeHost/Execute"
	CodeModeHost_Wait_FullMethodName                    = "/codex.code_mode.v1.CodeModeHost/Wait"
	CodeModeHost_CancelWait_FullMethodName              = "/codex.code_mode.v1.CodeModeHost/CancelWait"
	CodeModeHost_Terminate_FullMethodName               = "/codex.code_mode.v1.CodeModeHost/Terminate"
)

// CodeModeHostClient is the client API for CodeModeHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Hosts stateful JavaScript execution and delegates nested tool calls to the
// session owner. Large tool inputs and outputs stay off the session event
// stream so independent HTTP/2 streams can make progress concurrently.
type CodeModeHostClient interface {
	// Generic framing transport: carries the code-mode IPC JSON framing over a
	// single bidirectional gRPC stream. Used when a host exposes the same
	// protocol over gRPC instead of WebSocket or stdio.
	Transport(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FramedMessage, FramedMessage], error)
	// Opens a session lease. The first event is always SessionOpened; dropping
	// this stream closes the session and terminates its active cells.
	OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionEvent], error)
	CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	// Each subscription owns an independent stream of matching invocations. An
	// empty tool_names filter matches every tool. Each invocation is routed to
	// exactly one matching subscription, even when filters overlap.
	SubscribeToToolCalls(ctx context.Context, in *SubscribeToToolCallsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolCall], error)
	// Each result receives its own HTTP/2 stream, preventing a large response
	// from blocking unrelated tool completions or session control events.
	CompleteToolCall(ctx context.Context, in *CompleteToolCallRequest, opts ...grpc.CallOption) (*CompleteToolCallResponse, error)
	AcknowledgeNotification(ctx context.Context, in *AcknowledgeNotificationRequest, opts ...grpc.CallOption) (*AcknowledgeNotificationResponse, error)
	// Emits ExecutionStarted immediately, followed by one ExecutionOutcome when
	// the execution yields, completes, or is terminated.
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteEvent], error)
	Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error)
	// Acknowledges that a canceled wait has retired before another wait starts.
	CancelWait(ctx context.Context, in *CancelWaitRequest, opts ...grpc.CallOption) (*CancelWaitResponse, error)
	Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*WaitResponse, error)
}

type codeModeHostClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeModeHostClient(cc grpc.ClientConnInterface) CodeModeHostClient {
	return &codeModeHostClient{cc}
}

func (c *codeModeHostClient) Transport(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FramedMessage, FramedMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CodeModeHost_ServiceDesc.Streams[0], CodeModeHost_Transport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FramedMessage, FramedMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeModeHost_TransportClient = grpc.BidiStreamingClient[FramedMessage, FramedMessage]

func (c *codeModeHostClient) OpenSession(ctx context.Context, in *OpenSessionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SessionEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CodeModeHost_ServiceDesc.Streams[1], CodeModeHost_OpenSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OpenSessionRequest, SessionEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeModeHost_OpenSessionClient = grpc.ServerStreamingClient[SessionEvent]

func (c *codeModeHostClient) CloseSession(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, CodeModeHost_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeModeHostClient) SubscribeToToolCalls(ctx context.Context, in *SubscribeToToolCallsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolCall], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CodeModeHost_ServiceDesc.Streams[2], CodeModeHost_SubscribeToToolCalls_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToToolCallsRequest, ToolCall]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeModeHost_SubscribeToToolCallsClient = grpc.ServerStreamingClient[ToolCall]

func (c *codeModeHostClient) CompleteToolCall(ctx context.Context, in *CompleteToolCallRequest, opts ...grpc.CallOption) (*CompleteToolCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteToolCallResponse)
	err := c.cc.Invoke(ctx, CodeModeHost_CompleteToolCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeModeHostClient) AcknowledgeNotification(ctx context.Context, in *AcknowledgeNotificationRequest, opts ...grpc.CallOption) (*AcknowledgeNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeNotificationResponse)
	err := c.cc.Invoke(ctx, CodeModeHost_AcknowledgeNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeModeHostClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CodeModeHost_ServiceDesc.Streams[3], CodeModeHost_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeModeHost_ExecuteClient = grpc.ServerStreamingClient[ExecuteEvent]

func (c *codeModeHostClient) Wait(ctx context.Context, in *WaitRequest, opts ...grpc.CallOption) (*WaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitResponse)
	err := c.cc.Invoke(ctx, CodeModeHost_Wait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeModeHostClient) CancelWait(ctx context.Context, in *CancelWaitRequest, opts ...grpc.CallOption) (*CancelWaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelWaitResponse)
	err := c.cc.Invoke(ctx, CodeModeHost_CancelWait_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *codeModeHostClient) Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*WaitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitResponse)
	err := c.cc.Invoke(ctx, CodeModeHost_Terminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeModeHostServer is the server API for CodeModeHost service.
// All implementations must embed UnimplementedCodeModeHostServer
// for forward compatibility.
//
// Hosts stateful JavaScript execution and delegates nested tool calls to the
// session owner. Large tool inputs and outputs stay off the session event
// stream so independent HTTP/2 streams can make progress concurrently.
type CodeModeHostServer interface {
	// Generic framing transport: carries the code-mode IPC JSON framing over a
	// single bidirectional gRPC stream. Used when a host exposes the same
	// protocol over gRPC instead of WebSocket or stdio.
	Transport(grpc.BidiStreamingServer[FramedMessage, FramedMessage]) error
	// Opens a session lease. The first event is always SessionOpened; dropping
	// this stream closes the session and terminates its active cells.
	OpenSession(*OpenSessionRequest, grpc.ServerStreamingServer[SessionEvent]) error
	CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	// Each subscription owns an independent stream of matching invocations. An
	// empty tool_names filter matches every tool. Each invocation is routed to
	// exactly one matching subscription, even when filters overlap.
	SubscribeToToolCalls(*SubscribeToToolCallsRequest, grpc.ServerStreamingServer[ToolCall]) error
	// Each result receives its own HTTP/2 stream, preventing a large response
	// from blocking unrelated tool completions or session control events.
	CompleteToolCall(context.Context, *CompleteToolCallRequest) (*CompleteToolCallResponse, error)
	AcknowledgeNotification(context.Context, *AcknowledgeNotificationRequest) (*AcknowledgeNotificationResponse, error)
	// Emits ExecutionStarted immediately, followed by one ExecutionOutcome when
	// the execution yields, completes, or is terminated.
	Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteEvent]) error
	Wait(context.Context, *WaitRequest) (*WaitResponse, error)
	// Acknowledges that a canceled wait has retired before another wait starts.
	CancelWait(context.Context, *CancelWaitRequest) (*CancelWaitResponse, error)
	Terminate(context.Context, *TerminateRequest) (*WaitResponse, error)
	mustEmbedUnimplementedCodeModeHostServer()
}

// UnimplementedCodeModeHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeModeHostServer struct{}

func (UnimplementedCodeModeHostServer) Transport(grpc.BidiStreamingServer[FramedMessage, FramedMessage]) error {
	return status.Error(codes.Unimplemented, "method Transport not implemented")
}
func (UnimplementedCodeModeHostServer) OpenSession(*OpenSessionRequest, grpc.ServerStreamingServer[SessionEvent]) error {
	return status.Error(codes.Unimplemented, "method OpenSession not implemented")
}
func (UnimplementedCodeModeHostServer) CloseSession(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedCodeModeHostServer) SubscribeToToolCalls(*SubscribeToToolCallsRequest, grpc.ServerStreamingServer[ToolCall]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToToolCalls not implemented")
}
func (UnimplementedCodeModeHostServer) CompleteToolCall(context.Context, *CompleteToolCallRequest) (*CompleteToolCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteToolCall not implemented")
}
func (UnimplementedCodeModeHostServer) AcknowledgeNotification(context.Context, *AcknowledgeNotificationRequest) (*AcknowledgeNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeNotification not implemented")
}
func (UnimplementedCodeModeHostServer) Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteEvent]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCodeModeHostServer) Wait(context.Context, *WaitRequest) (*WaitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Wait not implemented")
}
func (UnimplementedCodeModeHostServer) CancelWait(context.Context, *CancelWaitRequest) (*CancelWaitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelWait not implemented")
}
func (UnimplementedCodeModeHostServer) Terminate(context.Context, *TerminateRequest) (*WaitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Terminate not implemented")
}
func (UnimplementedCodeModeHostServer) mustEmbedUnimplementedCodeModeHostServer() {}
func (UnimplementedCodeModeHostServer) testEmbeddedByValue()                      {}

// UnsafeCodeModeHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeModeHostServer will
// result in compilation errors.
type UnsafeCodeModeHostServer interface {
	mustEmbedUnimplementedCodeModeHostServer()
}

func RegisterCodeModeHostServer(s grpc.ServiceRegistrar, srv CodeModeHostServer) {
	// If the following call panics, it indicates UnimplementedCodeModeHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeModeHost_ServiceDesc, srv)
}

func _CodeModeHost_Transport_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CodeModeHostServer).Transport(&grpc.GenericServerStream[FramedMessage, FramedMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeModeHost_TransportServer = grpc.BidiStreamingServer[FramedMessage, FramedMessage]

func _CodeModeHost_OpenSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OpenSessionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CodeModeHostServer).OpenSession(m, &grpc.GenericServerStream[OpenSessionRequest, SessionEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeModeHost_OpenSessionServer = grpc.ServerStreamingServer[SessionEvent]

func _CodeModeHost_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeModeHostServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeModeHost_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeModeHostServer).CloseSession(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeModeHost_SubscribeToToolCalls_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToToolCallsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CodeModeHostServer).SubscribeToToolCalls(m, &grpc.GenericServerStream[SubscribeToToolCallsRequest, ToolCall]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeModeHost_SubscribeToToolCallsServer = grpc.ServerStreamingServer[ToolCall]

func _CodeModeHost_CompleteToolCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteToolCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeModeHostServer).CompleteToolCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeModeHost_CompleteToolCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeModeHostServer).CompleteToolCall(ctx, req.(*CompleteToolCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeModeHost_AcknowledgeNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeModeHostServer).AcknowledgeNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeModeHost_AcknowledgeNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeModeHostServer).AcknowledgeNotification(ctx, req.(*AcknowledgeNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeModeHost_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CodeModeHostServer).Execute(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CodeModeHost_ExecuteServer = grpc.ServerStreamingServer[ExecuteEvent]

func _CodeModeHost_Wait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeModeHostServer).Wait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeModeHost_Wait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeModeHostServer).Wait(ctx, req.(*WaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeModeHost_CancelWait_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWaitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeModeHostServer).CancelWait(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeModeHost_CancelWait_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeModeHostServer).CancelWait(ctx, req.(*CancelWaitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CodeModeHost_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeModeHostServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeModeHost_Terminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeModeHostServer).Terminate(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeModeHost_ServiceDesc is the grpc.ServiceDesc for CodeModeHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeModeHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "codex.code_mode.v1.CodeModeHost",
	HandlerType: (*CodeModeHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseSession",
			Handler:    _CodeModeHost_CloseSession_Handler,
		},
		{
			MethodName: "CompleteToolCall",
			Handler:    _CodeModeHost_CompleteToolCall_Handler,
		},
		{
			MethodName: "AcknowledgeNotification",
			Handler:    _CodeModeHost_AcknowledgeNotification_Handler,
		},
		{
			MethodName: "Wait",
			Handler:    _CodeModeHost_Wait_Handler,
		},
		{
			MethodName: "CancelWait",
			Handler:    _CodeModeHost_CancelWait_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _CodeModeHost_Terminate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transport",
			Handler:       _CodeModeHost_Transport_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenSession",
			Handler:       _CodeModeHost_OpenSession_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeToToolCalls",
			Handler:       _CodeModeHost_SubscribeToToolCalls_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Execute",
			Handler:       _CodeModeHost_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "codex.code_mode.v1.proto",
}
