// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: codex.code_mode.v1.proto

package codemodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToolKind int32

const (
	ToolKind_TOOL_KIND_UNSPECIFIED ToolKind = 0
	ToolKind_TOOL_KIND_FUNCTION    ToolKind = 1
	ToolKind_TOOL_KIND_FREEFORM    ToolKind = 2
)

// Enum value maps for ToolKind.
var (
	ToolKind_name = map[int32]string{
		0: "TOOL_KIND_UNSPECIFIED",
		1: "TOOL_KIND_FUNCTION",
		2: "TOOL_KIND_FREEFORM",
	}
	ToolKind_value = map[string]int32{
		"TOOL_KIND_UNSPECIFIED": 0,
		"TOOL_KIND_FUNCTION":    1,
		"TOOL_KIND_FREEFORM":    2,
	}
)

func (x ToolKind) Enum() *ToolKind {
	p := new(ToolKind)
	*p = x
	return p
}

func (x ToolKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolKind) Descriptor() protoreflect.EnumDescriptor {
	return file_codex_code_mode_v1_proto_enumTypes[0].Descriptor()
}

func (ToolKind) Type() protoreflect.EnumType {
	return &file_codex_code_mode_v1_proto_enumTypes[0]
}

func (x ToolKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolKind.Descriptor instead.
func (ToolKind) EnumDescriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{0}
}

type ImageDetail int32

const (
	ImageDetail_IMAGE_DETAIL_UNSPECIFIED ImageDetail = 0
	ImageDetail_IMAGE_DETAIL_AUTO        ImageDetail = 1
	ImageDetail_IMAGE_DETAIL_LOW         ImageDetail = 2
	ImageDetail_IMAGE_DETAIL_HIGH        ImageDetail = 3
	ImageDetail_IMAGE_DETAIL_ORIGINAL    ImageDetail = 4
)

// Enum value maps for ImageDetail.
var (
	ImageDetail_name = map[int32]string{
		0: "IMAGE_DETAIL_UNSPECIFIED",
		1: "IMAGE_DETAIL_AUTO",
		2: "IMAGE_DETAIL_LOW",
		3: "IMAGE_DETAIL_HIGH",
		4: "IMAGE_DETAIL_ORIGINAL",
	}
	ImageDetail_value = map[string]int32{
		"IMAGE_DETAIL_UNSPECIFIED": 0,
		"IMAGE_DETAIL_AUTO":        1,
		"IMAGE_DETAIL_LOW":         2,
		"IMAGE_DETAIL_HIGH":        3,
		"IMAGE_DETAIL_ORIGINAL":    4,
	}
)

func (x ImageDetail) Enum() *ImageDetail {
	p := new(ImageDetail)
	*p = x
	return p
}

func (x ImageDetail) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageDetail) Descriptor() protoreflect.EnumDescriptor {
	return file_codex_code_mode_v1_proto_enumTypes[1].Descriptor()
}

func (ImageDetail) Type() protoreflect.EnumType {
	return &file_codex_code_mode_v1_proto_enumTypes[1]
}

func (x ImageDetail) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageDetail.Descriptor instead.
func (ImageDetail) EnumDescriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{1}
}

// FramedMessage carries one code-mode IPC framing payload (JSON) over the
// generic Transport stream.
type FramedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FramedMessage) Reset() {
	*x = FramedMessage{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FramedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FramedMessage) ProtoMessage() {}

func (x *FramedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FramedMessage.ProtoReflect.Descriptor instead.
func (*FramedMessage) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{0}
}

func (x *FramedMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OpenSessionRequest struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	CellExecutionLimits *SessionCellExecutionLimits `protobuf:"bytes,1,opt,name=cell_execution_limits,json=cellExecutionLimits,proto3,oneof" json:"cell_execution_limits,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{1}
}

func (x *OpenSessionRequest) GetCellExecutionLimits() *SessionCellExecutionLimits {
	if x != nil {
		return x.CellExecutionLimits
	}
	return nil
}

type SessionCellExecutionLimits struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MaxYieldTimeMs   *uint64                `protobuf:"varint,1,opt,name=max_yield_time_ms,json=maxYieldTimeMs,proto3,oneof" json:"max_yield_time_ms,omitempty"`
	MaxHeapSizeBytes *uint64                `protobuf:"varint,2,opt,name=max_heap_size_bytes,json=maxHeapSizeBytes,proto3,oneof" json:"max_heap_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionCellExecutionLimits) Reset() {
	*x = SessionCellExecutionLimits{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCellExecutionLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCellExecutionLimits) ProtoMessage() {}

func (x *SessionCellExecutionLimits) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCellExecutionLimits.ProtoReflect.Descriptor instead.
func (*SessionCellExecutionLimits) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{2}
}

func (x *SessionCellExecutionLimits) GetMaxYieldTimeMs() uint64 {
	if x != nil && x.MaxYieldTimeMs != nil {
		return *x.MaxYieldTimeMs
	}
	return 0
}

func (x *SessionCellExecutionLimits) GetMaxHeapSizeBytes() uint64 {
	if x != nil && x.MaxHeapSizeBytes != nil {
		return *x.MaxHeapSizeBytes
	}
	return 0
}

type SessionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SessionEvent_Opened
	//	*SessionEvent_ToolCallCancelled
	//	*SessionEvent_Notification
	//	*SessionEvent_NotificationCancelled
	//	*SessionEvent_CellClosed
	Event         isSessionEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEvent) Reset() {
	*x = SessionEvent{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEvent) ProtoMessage() {}

func (x *SessionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEvent.ProtoReflect.Descriptor instead.
func (*SessionEvent) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{3}
}

func (x *SessionEvent) GetEvent() isSessionEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SessionEvent) GetOpened() *SessionOpened {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Opened); ok {
			return x.Opened
		}
	}
	return nil
}

func (x *SessionEvent) GetToolCallCancelled() *ToolCallCancelled {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_ToolCallCancelled); ok {
			return x.ToolCallCancelled
		}
	}
	return nil
}

func (x *SessionEvent) GetNotification() *Notification {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_Notification); ok {
			return x.Notification
		}
	}
	return nil
}

func (x *SessionEvent) GetNotificationCancelled() *NotificationCancelled {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_NotificationCancelled); ok {
			return x.NotificationCancelled
		}
	}
	return nil
}

func (x *SessionEvent) GetCellClosed() *CellClosed {
	if x != nil {
		if x, ok := x.Event.(*SessionEvent_CellClosed); ok {
			return x.CellClosed
		}
	}
	return nil
}

type isSessionEvent_Event interface {
	isSessionEvent_Event()
}

type SessionEvent_Opened struct {
	Opened *SessionOpened `protobuf:"bytes,1,opt,name=opened,proto3,oneof"`
}

type SessionEvent_ToolCallCancelled struct {
	ToolCallCancelled *ToolCallCancelled `protobuf:"bytes,2,opt,name=tool_call_cancelled,json=toolCallCancelled,proto3,oneof"`
}

type SessionEvent_Notification struct {
	Notification *Notification `protobuf:"bytes,3,opt,name=notification,proto3,oneof"`
}

type SessionEvent_NotificationCancelled struct {
	NotificationCancelled *NotificationCancelled `protobuf:"bytes,4,opt,name=notification_cancelled,json=notificationCancelled,proto3,oneof"`
}

type SessionEvent_CellClosed struct {
	CellClosed *CellClosed `protobuf:"bytes,5,opt,name=cell_closed,json=cellClosed,proto3,oneof"`
}

func (*SessionEvent_Opened) isSessionEvent_Event() {}

func (*SessionEvent_ToolCallCancelled) isSessionEvent_Event() {}

func (*SessionEvent_Notification) isSessionEvent_Event() {}

func (*SessionEvent_NotificationCancelled) isSessionEvent_Event() {}

func (*SessionEvent_CellClosed) isSessionEvent_Event() {}

type SessionOpened struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpened) Reset() {
	*x = SessionOpened{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpened) ProtoMessage() {}

func (x *SessionOpened) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpened.ProtoReflect.Descriptor instead.
func (*SessionOpened) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{4}
}

func (x *SessionOpened) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{5}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{6}
}

type SubscribeToToolCallsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ToolNames     []*ToolName            `protobuf:"bytes,2,rep,name=tool_names,json=toolNames,proto3" json:"tool_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToToolCallsRequest) Reset() {
	*x = SubscribeToToolCallsRequest{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToToolCallsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToToolCallsRequest) ProtoMessage() {}

func (x *SubscribeToToolCallsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToToolCallsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToToolCallsRequest) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeToToolCallsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SubscribeToToolCallsRequest) GetToolNames() []*ToolName {
	if x != nil {
		return x.ToolNames
	}
	return nil
}

type ToolCall struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Correlates callbacks with Execute before ExecutionStarted is received.
	ExecutionId       string    `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	CellId            string    `protobuf:"bytes,3,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	InvocationId      string    `protobuf:"bytes,4,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	RuntimeToolCallId string    `protobuf:"bytes,5,opt,name=runtime_tool_call_id,json=runtimeToolCallId,proto3" json:"runtime_tool_call_id,omitempty"`
	ToolName          *ToolName `protobuf:"bytes,6,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolKind          ToolKind  `protobuf:"varint,7,opt,name=tool_kind,json=toolKind,proto3,enum=codex.code_mode.v1.ToolKind" json:"tool_kind,omitempty"`
	InputJson         []byte    `protobuf:"bytes,8,opt,name=input_json,json=inputJson,proto3,oneof" json:"input_json,omitempty"`
	// Starts at one and increases independently for each execution.
	Sequence      uint64 `protobuf:"varint,9,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{8}
}

func (x *ToolCall) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ToolCall) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ToolCall) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *ToolCall) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *ToolCall) GetRuntimeToolCallId() string {
	if x != nil {
		return x.RuntimeToolCallId
	}
	return ""
}

func (x *ToolCall) GetToolName() *ToolName {
	if x != nil {
		return x.ToolName
	}
	return nil
}

func (x *ToolCall) GetToolKind() ToolKind {
	if x != nil {
		return x.ToolKind
	}
	return ToolKind_TOOL_KIND_UNSPECIFIED
}

func (x *ToolCall) GetInputJson() []byte {
	if x != nil {
		return x.InputJson
	}
	return nil
}

func (x *ToolCall) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type CompleteToolCallRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SessionId    string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InvocationId string                 `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*CompleteToolCallRequest_Succeeded
	//	*CompleteToolCallRequest_Failed
	Outcome       isCompleteToolCallRequest_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteToolCallRequest) Reset() {
	*x = CompleteToolCallRequest{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteToolCallRequest) ProtoMessage() {}

func (x *CompleteToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteToolCallRequest.ProtoReflect.Descriptor instead.
func (*CompleteToolCallRequest) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteToolCallRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteToolCallRequest) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *CompleteToolCallRequest) GetOutcome() isCompleteToolCallRequest_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *CompleteToolCallRequest) GetSucceeded() *ToolCallSucceeded {
	if x != nil {
		if x, ok := x.Outcome.(*CompleteToolCallRequest_Succeeded); ok {
			return x.Succeeded
		}
	}
	return nil
}

func (x *CompleteToolCallRequest) GetFailed() *ToolCallFailed {
	if x != nil {
		if x, ok := x.Outcome.(*CompleteToolCallRequest_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

type isCompleteToolCallRequest_Outcome interface {
	isCompleteToolCallRequest_Outcome()
}

type CompleteToolCallRequest_Succeeded struct {
	Succeeded *ToolCallSucceeded `protobuf:"bytes,3,opt,name=succeeded,proto3,oneof"`
}

type CompleteToolCallRequest_Failed struct {
	Failed *ToolCallFailed `protobuf:"bytes,4,opt,name=failed,proto3,oneof"`
}

func (*CompleteToolCallRequest_Succeeded) isCompleteToolCallRequest_Outcome() {}

func (*CompleteToolCallRequest_Failed) isCompleteToolCallRequest_Outcome() {}

type ToolCallSucceeded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputJson    []byte                 `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallSucceeded) Reset() {
	*x = ToolCallSucceeded{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallSucceeded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallSucceeded) ProtoMessage() {}

func (x *ToolCallSucceeded) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallSucceeded.ProtoReflect.Descriptor instead.
func (*ToolCallSucceeded) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{10}
}

func (x *ToolCallSucceeded) GetOutputJson() []byte {
	if x != nil {
		return x.OutputJson
	}
	return nil
}

type ToolCallFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallFailed) Reset() {
	*x = ToolCallFailed{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallFailed) ProtoMessage() {}

func (x *ToolCallFailed) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallFailed.ProtoReflect.Descriptor instead.
func (*ToolCallFailed) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{11}
}

func (x *ToolCallFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CompleteToolCallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteToolCallResponse) Reset() {
	*x = CompleteToolCallResponse{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteToolCallResponse) ProtoMessage() {}

func (x *CompleteToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteToolCallResponse.ProtoReflect.Descriptor instead.
func (*CompleteToolCallResponse) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{12}
}

type ToolCallCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallCancelled) Reset() {
	*x = ToolCallCancelled{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallCancelled) ProtoMessage() {}

func (x *ToolCallCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallCancelled.ProtoReflect.Descriptor instead.
func (*ToolCallCancelled) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{13}
}

func (x *ToolCallCancelled) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	ExecutionId    string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	CellId         string                 `protobuf:"bytes,3,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	CallId         string                 `protobuf:"bytes,4,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Text           string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{14}
}

func (x *Notification) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *Notification) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Notification) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *Notification) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Notification) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type NotificationCancelled struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationCancelled) Reset() {
	*x = NotificationCancelled{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationCancelled) ProtoMessage() {}

func (x *NotificationCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationCancelled.ProtoReflect.Descriptor instead.
func (*NotificationCancelled) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{15}
}

func (x *NotificationCancelled) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type AcknowledgeNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcknowledgeNotificationRequest) Reset() {
	*x = AcknowledgeNotificationRequest{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeNotificationRequest) ProtoMessage() {}

func (x *AcknowledgeNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeNotificationRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeNotificationRequest) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{16}
}

func (x *AcknowledgeNotificationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AcknowledgeNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type AcknowledgeNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeNotificationResponse) Reset() {
	*x = AcknowledgeNotificationResponse{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeNotificationResponse) ProtoMessage() {}

func (x *AcknowledgeNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeNotificationResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeNotificationResponse) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{17}
}

type CellClosed struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	CellId      string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	// All lower sequences must be observed before the client retires the cell.
	FinalToolCallSequence uint64 `protobuf:"varint,3,opt,name=final_tool_call_sequence,json=finalToolCallSequence,proto3" json:"final_tool_call_sequence,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CellClosed) Reset() {
	*x = CellClosed{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellClosed) ProtoMessage() {}

func (x *CellClosed) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellClosed.ProtoReflect.Descriptor instead.
func (*CellClosed) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{18}
}

func (x *CellClosed) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CellClosed) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *CellClosed) GetFinalToolCallSequence() uint64 {
	if x != nil {
		return x.FinalToolCallSequence
	}
	return 0
}

type ExecuteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Chosen by the client so callbacks can be correlated before cell admission.
	ExecutionId     string            `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	ToolCallId      string            `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	Source          string            `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	EnabledTools    []*ToolDefinition `protobuf:"bytes,5,rep,name=enabled_tools,json=enabledTools,proto3" json:"enabled_tools,omitempty"`
	YieldTimeMs     *uint64           `protobuf:"varint,6,opt,name=yield_time_ms,json=yieldTimeMs,proto3,oneof" json:"yield_time_ms,omitempty"`
	MaxOutputTokens *uint64           `protobuf:"varint,7,opt,name=max_output_tokens,json=maxOutputTokens,proto3,oneof" json:"max_output_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{19}
}

func (x *ExecuteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecuteRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteRequest) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ExecuteRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ExecuteRequest) GetEnabledTools() []*ToolDefinition {
	if x != nil {
		return x.EnabledTools
	}
	return nil
}

func (x *ExecuteRequest) GetYieldTimeMs() uint64 {
	if x != nil && x.YieldTimeMs != nil {
		return *x.YieldTimeMs
	}
	return 0
}

func (x *ExecuteRequest) GetMaxOutputTokens() uint64 {
	if x != nil && x.MaxOutputTokens != nil {
		return *x.MaxOutputTokens
	}
	return 0
}

type ExecuteEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecuteEvent_Started
	//	*ExecuteEvent_Outcome
	Event         isExecuteEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEvent) Reset() {
	*x = ExecuteEvent{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEvent) ProtoMessage() {}

func (x *ExecuteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEvent.ProtoReflect.Descriptor instead.
func (*ExecuteEvent) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{20}
}

func (x *ExecuteEvent) GetEvent() isExecuteEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecuteEvent) GetStarted() *ExecutionStarted {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *ExecuteEvent) GetOutcome() *ExecutionOutcome {
	if x != nil {
		if x, ok := x.Event.(*ExecuteEvent_Outcome); ok {
			return x.Outcome
		}
	}
	return nil
}

type isExecuteEvent_Event interface {
	isExecuteEvent_Event()
}

type ExecuteEvent_Started struct {
	Started *ExecutionStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type ExecuteEvent_Outcome struct {
	Outcome *ExecutionOutcome `protobuf:"bytes,2,opt,name=outcome,proto3,oneof"`
}

func (*ExecuteEvent_Started) isExecuteEvent_Event() {}

func (*ExecuteEvent_Outcome) isExecuteEvent_Event() {}

type ExecutionStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionStarted) Reset() {
	*x = ExecutionStarted{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionStarted) ProtoMessage() {}

func (x *ExecutionStarted) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionStarted.ProtoReflect.Descriptor instead.
func (*ExecutionStarted) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{21}
}

func (x *ExecutionStarted) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionStarted) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

type WaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	WaitId        string                 `protobuf:"bytes,3,opt,name=wait_id,json=waitId,proto3" json:"wait_id,omitempty"`
	YieldTimeMs   uint64                 `protobuf:"varint,4,opt,name=yield_time_ms,json=yieldTimeMs,proto3" json:"yield_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitRequest) Reset() {
	*x = WaitRequest{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitRequest) ProtoMessage() {}

func (x *WaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitRequest.ProtoReflect.Descriptor instead.
func (*WaitRequest) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{22}
}

func (x *WaitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WaitRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *WaitRequest) GetWaitId() string {
	if x != nil {
		return x.WaitId
	}
	return ""
}

func (x *WaitRequest) GetYieldTimeMs() uint64 {
	if x != nil {
		return x.YieldTimeMs
	}
	return 0
}

type WaitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*WaitResponse_LiveCell
	//	*WaitResponse_MissingCell
	State         isWaitResponse_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitResponse) Reset() {
	*x = WaitResponse{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitResponse) ProtoMessage() {}

func (x *WaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitResponse.ProtoReflect.Descriptor instead.
func (*WaitResponse) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{23}
}

func (x *WaitResponse) GetState() isWaitResponse_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *WaitResponse) GetLiveCell() *ExecutionOutcome {
	if x != nil {
		if x, ok := x.State.(*WaitResponse_LiveCell); ok {
			return x.LiveCell
		}
	}
	return nil
}

func (x *WaitResponse) GetMissingCell() *ExecutionOutcome {
	if x != nil {
		if x, ok := x.State.(*WaitResponse_MissingCell); ok {
			return x.MissingCell
		}
	}
	return nil
}

type isWaitResponse_State interface {
	isWaitResponse_State()
}

type WaitResponse_LiveCell struct {
	LiveCell *ExecutionOutcome `protobuf:"bytes,1,opt,name=live_cell,json=liveCell,proto3,oneof"`
}

type WaitResponse_MissingCell struct {
	MissingCell *ExecutionOutcome `protobuf:"bytes,2,opt,name=missing_cell,json=missingCell,proto3,oneof"`
}

func (*WaitResponse_LiveCell) isWaitResponse_State() {}

func (*WaitResponse_MissingCell) isWaitResponse_State() {}

type CancelWaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WaitId        string                 `protobuf:"bytes,2,opt,name=wait_id,json=waitId,proto3" json:"wait_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWaitRequest) Reset() {
	*x = CancelWaitRequest{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWaitRequest) ProtoMessage() {}

func (x *CancelWaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWaitRequest.ProtoReflect.Descriptor instead.
func (*CancelWaitRequest) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{24}
}

func (x *CancelWaitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CancelWaitRequest) GetWaitId() string {
	if x != nil {
		return x.WaitId
	}
	return ""
}

type CancelWaitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWaitResponse) Reset() {
	*x = CancelWaitResponse{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWaitResponse) ProtoMessage() {}

func (x *CancelWaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWaitResponse.ProtoReflect.Descriptor instead.
func (*CancelWaitResponse) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{25}
}

type TerminateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CellId        string                 `protobuf:"bytes,2,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateRequest) Reset() {
	*x = TerminateRequest{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateRequest) ProtoMessage() {}

func (x *TerminateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateRequest.ProtoReflect.Descriptor instead.
func (*TerminateRequest) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{26}
}

func (x *TerminateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminateRequest) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

type ExecutionOutcome struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	CellId       string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	ContentItems []*ContentItem         `protobuf:"bytes,2,rep,name=content_items,json=contentItems,proto3" json:"content_items,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*ExecutionOutcome_Yielded
	//	*ExecutionOutcome_Terminated
	//	*ExecutionOutcome_Completed
	Outcome       isExecutionOutcome_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionOutcome) Reset() {
	*x = ExecutionOutcome{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionOutcome) ProtoMessage() {}

func (x *ExecutionOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionOutcome.ProtoReflect.Descriptor instead.
func (*ExecutionOutcome) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{27}
}

func (x *ExecutionOutcome) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *ExecutionOutcome) GetContentItems() []*ContentItem {
	if x != nil {
		return x.ContentItems
	}
	return nil
}

func (x *ExecutionOutcome) GetOutcome() isExecutionOutcome_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *ExecutionOutcome) GetYielded() *ExecutionYielded {
	if x != nil {
		if x, ok := x.Outcome.(*ExecutionOutcome_Yielded); ok {
			return x.Yielded
		}
	}
	return nil
}

func (x *ExecutionOutcome) GetTerminated() *ExecutionTerminated {
	if x != nil {
		if x, ok := x.Outcome.(*ExecutionOutcome_Terminated); ok {
			return x.Terminated
		}
	}
	return nil
}

func (x *ExecutionOutcome) GetCompleted() *ExecutionCompleted {
	if x != nil {
		if x, ok := x.Outcome.(*ExecutionOutcome_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

type isExecutionOutcome_Outcome interface {
	isExecutionOutcome_Outcome()
}

type ExecutionOutcome_Yielded struct {
	Yielded *ExecutionYielded `protobuf:"bytes,3,opt,name=yielded,proto3,oneof"`
}

type ExecutionOutcome_Terminated struct {
	Terminated *ExecutionTerminated `protobuf:"bytes,4,opt,name=terminated,proto3,oneof"`
}

type ExecutionOutcome_Completed struct {
	Completed *ExecutionCompleted `protobuf:"bytes,5,opt,name=completed,proto3,oneof"`
}

func (*ExecutionOutcome_Yielded) isExecutionOutcome_Outcome() {}

func (*ExecutionOutcome_Terminated) isExecutionOutcome_Outcome() {}

func (*ExecutionOutcome_Completed) isExecutionOutcome_Outcome() {}

type ExecutionYielded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionYielded) Reset() {
	*x = ExecutionYielded{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionYielded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionYielded) ProtoMessage() {}

func (x *ExecutionYielded) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionYielded.ProtoReflect.Descriptor instead.
func (*ExecutionYielded) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{28}
}

type ExecutionTerminated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionTerminated) Reset() {
	*x = ExecutionTerminated{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTerminated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTerminated) ProtoMessage() {}

func (x *ExecutionTerminated) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTerminated.ProtoReflect.Descriptor instead.
func (*ExecutionTerminated) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{29}
}

type ExecutionCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorText     *string                `protobuf:"bytes,1,opt,name=error_text,json=errorText,proto3,oneof" json:"error_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionCompleted) Reset() {
	*x = ExecutionCompleted{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionCompleted) ProtoMessage() {}

func (x *ExecutionCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionCompleted.ProtoReflect.Descriptor instead.
func (*ExecutionCompleted) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{30}
}

func (x *ExecutionCompleted) GetErrorText() string {
	if x != nil && x.ErrorText != nil {
		return *x.ErrorText
	}
	return ""
}

type ToolDefinition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ToolName         *ToolName              `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Kind             ToolKind               `protobuf:"varint,4,opt,name=kind,proto3,enum=codex.code_mode.v1.ToolKind" json:"kind,omitempty"`
	InputSchemaJson  []byte                 `protobuf:"bytes,5,opt,name=input_schema_json,json=inputSchemaJson,proto3,oneof" json:"input_schema_json,omitempty"`
	OutputSchemaJson []byte                 `protobuf:"bytes,6,opt,name=output_schema_json,json=outputSchemaJson,proto3,oneof" json:"output_schema_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{31}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetToolName() *ToolName {
	if x != nil {
		return x.ToolName
	}
	return nil
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetKind() ToolKind {
	if x != nil {
		return x.Kind
	}
	return ToolKind_TOOL_KIND_UNSPECIFIED
}

func (x *ToolDefinition) GetInputSchemaJson() []byte {
	if x != nil {
		return x.InputSchemaJson
	}
	return nil
}

func (x *ToolDefinition) GetOutputSchemaJson() []byte {
	if x != nil {
		return x.OutputSchemaJson
	}
	return nil
}

type ToolName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     *string                `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolName) Reset() {
	*x = ToolName{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolName) ProtoMessage() {}

func (x *ToolName) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolName.ProtoReflect.Descriptor instead.
func (*ToolName) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{32}
}

func (x *ToolName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolName) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type ContentItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*ContentItem_Text
	//	*ContentItem_Image
	//	*ContentItem_Audio
	Item          isContentItem_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentItem) Reset() {
	*x = ContentItem{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentItem) ProtoMessage() {}

func (x *ContentItem) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentItem.ProtoReflect.Descriptor instead.
func (*ContentItem) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{33}
}

func (x *ContentItem) GetItem() isContentItem_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ContentItem) GetText() *TextContent {
	if x != nil {
		if x, ok := x.Item.(*ContentItem_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *ContentItem) GetImage() *ImageContent {
	if x != nil {
		if x, ok := x.Item.(*ContentItem_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *ContentItem) GetAudio() *AudioContent {
	if x != nil {
		if x, ok := x.Item.(*ContentItem_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

type isContentItem_Item interface {
	isContentItem_Item()
}

type ContentItem_Text struct {
	Text *TextContent `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type ContentItem_Image struct {
	Image *ImageContent `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

type ContentItem_Audio struct {
	Audio *AudioContent `protobuf:"bytes,3,opt,name=audio,proto3,oneof"`
}

func (*ContentItem_Text) isContentItem_Item() {}

func (*ContentItem_Image) isContentItem_Item() {}

func (*ContentItem_Audio) isContentItem_Item() {}

type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{34}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ImageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Detail        *ImageDetail           `protobuf:"varint,2,opt,name=detail,proto3,enum=codex.code_mode.v1.ImageDetail,oneof" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageContent) Reset() {
	*x = ImageContent{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageContent) ProtoMessage() {}

func (x *ImageContent) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageContent.ProtoReflect.Descriptor instead.
func (*ImageContent) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{35}
}

func (x *ImageContent) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ImageContent) GetDetail() ImageDetail {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ImageDetail_IMAGE_DETAIL_UNSPECIFIED
}

type AudioContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioUrl      string                 `protobuf:"bytes,1,opt,name=audio_url,json=audioUrl,proto3" json:"audio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioContent) Reset() {
	*x = AudioContent{}
	mi := &file_codex_code_mode_v1_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioContent) ProtoMessage() {}

func (x *AudioContent) ProtoReflect() protoreflect.Message {
	mi := &file_codex_code_mode_v1_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioContent.ProtoReflect.Descriptor instead.
func (*AudioContent) Descriptor() ([]byte, []int) {
	return file_codex_code_mode_v1_proto_rawDescGZIP(), []int{36}
}

func (x *AudioContent) GetAudioUrl() string {
	if x != nil {
		return x.AudioUrl
	}
	return ""
}

var File_codex_code_mode_v1_proto protoreflect.FileDescriptor

const file_codex_code_mode_v1_proto_rawDesc = "" +
	"\n" +
	"\x18codex.code_mode.v1.proto\x12\x12codex.code_mode.v1\")\n" +
	"\rFramedMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x97\x01\n" +
	"\x12OpenSessionRequest\x12g\n" +
	"\x15cell_execution_limits\x18\x01 \x01(\v2..codex.code_mode.v1.SessionCellExecutionLimitsH\x00R\x13cellExecutionLimits\x88\x01\x01B\x18\n" +
	"\x16_cell_execution_limits\"\xae\x01\n" +
	"\x1aSessionCellExecutionLimits\x12.\n" +
	"\x11max_yield_time_ms\x18\x01 \x01(\x04H\x00R\x0emaxYieldTimeMs\x88\x01\x01\x122\n" +
	"\x13max_heap_size_bytes\x18\x02 \x01(\x04H\x01R\x10maxHeapSizeBytes\x88\x01\x01B\x14\n" +
	"\x12_max_yield_time_msB\x16\n" +
	"\x14_max_heap_size_bytes\"\x9c\x03\n" +
	"\fSessionEvent\x12;\n" +
	"\x06opened\x18\x01 \x01(\v2!.codex.code_mode.v1.SessionOpenedH\x00R\x06opened\x12W\n" +
	"\x13tool_call_cancelled\x18\x02 \x01(\v2%.codex.code_mode.v1.ToolCallCancelledH\x00R\x11toolCallCancelled\x12F\n" +
	"\fnotification\x18\x03 \x01(\v2 .codex.code_mode.v1.NotificationH\x00R\fnotification\x12b\n" +
	"\x16notification_cancelled\x18\x04 \x01(\v2).codex.code_mode.v1.NotificationCancelledH\x00R\x15notificationCancelled\x12A\n" +
	"\vcell_closed\x18\x05 \x01(\v2\x1e.codex.code_mode.v1.CellClosedH\x00R\n" +
	"cellClosedB\a\n" +
	"\x05event\".\n" +
	"\rSessionOpened\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x16\n" +
	"\x14CloseSessionResponse\"y\n" +
	"\x1bSubscribeToToolCallsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\n" +
	"tool_names\x18\x02 \x03(\v2\x1c.codex.code_mode.v1.ToolNameR\ttoolNames\"\x80\x03\n" +
	"\bToolCall\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x17\n" +
	"\acell_id\x18\x03 \x01(\tR\x06cellId\x12#\n" +
	"\rinvocation_id\x18\x04 \x01(\tR\finvocationId\x12/\n" +
	"\x14runtime_tool_call_id\x18\x05 \x01(\tR\x11runtimeToolCallId\x129\n" +
	"\ttool_name\x18\x06 \x01(\v2\x1c.codex.code_mode.v1.ToolNameR\btoolName\x129\n" +
	"\ttool_kind\x18\a \x01(\x0e2\x1c.codex.code_mode.v1.ToolKindR\btoolKind\x12\"\n" +
	"\n" +
	"input_json\x18\b \x01(\fH\x00R\tinputJson\x88\x01\x01\x12\x1a\n" +
	"\bsequence\x18\t \x01(\x04R\bsequenceB\r\n" +
	"\v_input_json\"\xed\x01\n" +
	"\x17CompleteToolCallRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12E\n" +
	"\tsucceeded\x18\x03 \x01(\v2%.codex.code_mode.v1.ToolCallSucceededH\x00R\tsucceeded\x12<\n" +
	"\x06failed\x18\x04 \x01(\v2\".codex.code_mode.v1.ToolCallFailedH\x00R\x06failedB\t\n" +
	"\aoutcome\"4\n" +
	"\x11ToolCallSucceeded\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\fR\n" +
	"outputJson\"*\n" +
	"\x0eToolCallFailed\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1a\n" +
	"\x18CompleteToolCallResponse\"8\n" +
	"\x11ToolCallCancelled\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\"\xa0\x01\n" +
	"\fNotification\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x17\n" +
	"\acell_id\x18\x03 \x01(\tR\x06cellId\x12\x17\n" +
	"\acall_id\x18\x04 \x01(\tR\x06callId\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\"@\n" +
	"\x15NotificationCancelled\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"h\n" +
	"\x1eAcknowledgeNotificationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId\"!\n" +
	"\x1fAcknowledgeNotificationResponse\"\x81\x01\n" +
	"\n" +
	"CellClosed\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\x127\n" +
	"\x18final_tool_call_sequence\x18\x03 \x01(\x04R\x15finalToolCallSequence\"\xd7\x02\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12G\n" +
	"\renabled_tools\x18\x05 \x03(\v2\".codex.code_mode.v1.ToolDefinitionR\fenabledTools\x12'\n" +
	"\ryield_time_ms\x18\x06 \x01(\x04H\x00R\vyieldTimeMs\x88\x01\x01\x12/\n" +
	"\x11max_output_tokens\x18\a \x01(\x04H\x01R\x0fmaxOutputTokens\x88\x01\x01B\x10\n" +
	"\x0e_yield_time_msB\x14\n" +
	"\x12_max_output_tokens\"\x9b\x01\n" +
	"\fExecuteEvent\x12@\n" +
	"\astarted\x18\x01 \x01(\v2$.codex.code_mode.v1.ExecutionStartedH\x00R\astarted\x12@\n" +
	"\aoutcome\x18\x02 \x01(\v2$.codex.code_mode.v1.ExecutionOutcomeH\x00R\aoutcomeB\a\n" +
	"\x05event\"N\n" +
	"\x10ExecutionStarted\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\"\x82\x01\n" +
	"\vWaitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\x12\x17\n" +
	"\await_id\x18\x03 \x01(\tR\x06waitId\x12\"\n" +
	"\ryield_time_ms\x18\x04 \x01(\x04R\vyieldTimeMs\"\xa7\x01\n" +
	"\fWaitResponse\x12C\n" +
	"\tlive_cell\x18\x01 \x01(\v2$.codex.code_mode.v1.ExecutionOutcomeH\x00R\bliveCell\x12I\n" +
	"\fmissing_cell\x18\x02 \x01(\v2$.codex.code_mode.v1.ExecutionOutcomeH\x00R\vmissingCellB\a\n" +
	"\x05state\"K\n" +
	"\x11CancelWaitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\await_id\x18\x02 \x01(\tR\x06waitId\"\x14\n" +
	"\x12CancelWaitResponse\"J\n" +
	"\x10TerminateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\acell_id\x18\x02 \x01(\tR\x06cellId\"\xd1\x02\n" +
	"\x10ExecutionOutcome\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12D\n" +
	"\rcontent_items\x18\x02 \x03(\v2\x1f.codex.code_mode.v1.ContentItemR\fcontentItems\x12@\n" +
	"\ayielded\x18\x03 \x01(\v2$.codex.code_mode.v1.ExecutionYieldedH\x00R\ayielded\x12I\n" +
	"\n" +
	"terminated\x18\x04 \x01(\v2'.codex.code_mode.v1.ExecutionTerminatedH\x00R\n" +
	"terminated\x12F\n" +
	"\tcompleted\x18\x05 \x01(\v2&.codex.code_mode.v1.ExecutionCompletedH\x00R\tcompletedB\t\n" +
	"\aoutcome\"\x12\n" +
	"\x10ExecutionYielded\"\x15\n" +
	"\x13ExecutionTerminated\"G\n" +
	"\x12ExecutionCompleted\x12\"\n" +
	"\n" +
	"error_text\x18\x01 \x01(\tH\x00R\terrorText\x88\x01\x01B\r\n" +
	"\v_error_text\"\xc4\x02\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\ttool_name\x18\x02 \x01(\v2\x1c.codex.code_mode.v1.ToolNameR\btoolName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1c.codex.code_mode.v1.ToolKindR\x04kind\x12/\n" +
	"\x11input_schema_json\x18\x05 \x01(\fH\x00R\x0finputSchemaJson\x88\x01\x01\x121\n" +
	"\x12output_schema_json\x18\x06 \x01(\fH\x01R\x10outputSchemaJson\x88\x01\x01B\x14\n" +
	"\x12_input_schema_jsonB\x15\n" +
	"\x13_output_schema_json\"O\n" +
	"\bToolName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\tnamespace\x18\x02 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"\xc0\x01\n" +
	"\vContentItem\x125\n" +
	"\x04text\x18\x01 \x01(\v2\x1f.codex.code_mode.v1.TextContentH\x00R\x04text\x128\n" +
	"\x05image\x18\x02 \x01(\v2 .codex.code_mode.v1.ImageContentH\x00R\x05image\x128\n" +
	"\x05audio\x18\x03 \x01(\v2 .codex.code_mode.v1.AudioContentH\x00R\x05audioB\x06\n" +
	"\x04item\"!\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"t\n" +
	"\fImageContent\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl\x12<\n" +
	"\x06detail\x18\x02 \x01(\x0e2\x1f.codex.code_mode.v1.ImageDetailH\x00R\x06detail\x88\x01\x01B\t\n" +
	"\a_detail\"+\n" +
	"\fAudioContent\x12\x1b\n" +
	"\taudio_url\x18\x01 \x01(\tR\baudioUrl*U\n" +
	"\bToolKind\x12\x19\n" +
	"\x15TOOL_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TOOL_KIND_FUNCTION\x10\x01\x12\x16\n" +
	"\x12TOOL_KIND_FREEFORM\x10\x02*\x8a\x01\n" +
	"\vImageDetail\x12\x1c\n" +
	"\x18IMAGE_DETAIL_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11IMAGE_DETAIL_AUTO\x10\x01\x12\x14\n" +
	"\x10IMAGE_DETAIL_LOW\x10\x02\x12\x15\n" +
	"\x11IMAGE_DETAIL_HIGH\x10\x03\x12\x19\n" +
	"\x15IMAGE_DETAIL_ORIGINAL\x10\x042\xd0\a\n" +
	"\fCodeModeHost\x12U\n" +
	"\tTransport\x12!.codex.code_mode.v1.FramedMessage\x1a!.codex.code_mode.v1.FramedMessage(\x010\x01\x12Y\n" +
	"\vOpenSession\x12&.codex.code_mode.v1.OpenSessionRequest\x1a .codex.code_mode.v1.SessionEvent0\x01\x12a\n" +
	"\fCloseSession\x12'.codex.code_mode.v1.CloseSessionRequest\x1a(.codex.code_mode.v1.CloseSessionResponse\x12g\n" +
	"\x14SubscribeToToolCalls\x12/.codex.code_mode.v1.SubscribeToToolCallsRequest\x1a\x1c.codex.code_mode.v1.ToolCall0\x01\x12m\n" +
	"\x10CompleteToolCall\x12+.codex.code_mode.v1.CompleteToolCallRequest\x1a,.codex.code_mode.v1.CompleteToolCallResponse\x12\x82\x01\n" +
	"\x17AcknowledgeNotification\x122.codex.code_mode.v1.AcknowledgeNotificationRequest\x1a3.codex.code_mode.v1.AcknowledgeNotificationResponse\x12Q\n" +
	"\aExecute\x12\".codex.code_mode.v1.ExecuteRequest\x1a .codex.code_mode.v1.ExecuteEvent0\x01\x12I\n" +
	"\x04Wait\x12\x1f.codex.code_mode.v1.WaitRequest\x1a .codex.code_mode.v1.WaitResponse\x12[\n" +
	"\n" +
	"CancelWait\x12%.codex.code_mode.v1.CancelWaitRequest\x1a&.codex.code_mode.v1.CancelWaitResponse\x12S\n" +
	"\tTerminate\x12$.codex.code_mode.v1.TerminateRequest\x1a .codex.code_mode.v1.WaitResponseB#Z!codex_go/codemode/grpc/codemodev1b\x06proto3"

var (
	file_codex_code_mode_v1_proto_rawDescOnce sync.Once
	file_codex_code_mode_v1_proto_rawDescData []byte
)

func file_codex_code_mode_v1_proto_rawDescGZIP() []byte {
	file_codex_code_mode_v1_proto_rawDescOnce.Do(func() {
		file_codex_code_mode_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codex_code_mode_v1_proto_rawDesc), len(file_codex_code_mode_v1_proto_rawDesc)))
	})
	return file_codex_code_mode_v1_proto_rawDescData
}

var file_codex_code_mode_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_codex_code_mode_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_codex_code_mode_v1_proto_goTypes = []any{
	(ToolKind)(0),                           // 0: codex.code_mode.v1.ToolKind
	(ImageDetail)(0),                        // 1: codex.code_mode.v1.ImageDetail
	(*FramedMessage)(nil),                   // 2: codex.code_mode.v1.FramedMessage
	(*OpenSessionRequest)(nil),              // 3: codex.code_mode.v1.OpenSessionRequest
	(*SessionCellExecutionLimits)(nil),      // 4: codex.code_mode.v1.SessionCellExecutionLimits
	(*SessionEvent)(nil),                    // 5: codex.code_mode.v1.SessionEvent
	(*SessionOpened)(nil),                   // 6: codex.code_mode.v1.SessionOpened
	(*CloseSessionRequest)(nil),             // 7: codex.code_mode.v1.CloseSessionRequest
	(*CloseSessionResponse)(nil),            // 8: codex.code_mode.v1.CloseSessionResponse
	(*SubscribeToToolCallsRequest)(nil),     // 9: codex.code_mode.v1.SubscribeToToolCallsRequest
	(*ToolCall)(nil),                        // 10: codex.code_mode.v1.ToolCall
	(*CompleteToolCallRequest)(nil),         // 11: codex.code_mode.v1.CompleteToolCallRequest
	(*ToolCallSucceeded)(nil),               // 12: codex.code_mode.v1.ToolCallSucceeded
	(*ToolCallFailed)(nil),                  // 13: codex.code_mode.v1.ToolCallFailed
	(*CompleteToolCallResponse)(nil),        // 14: codex.code_mode.v1.CompleteToolCallResponse
	(*ToolCallCancelled)(nil),               // 15: codex.code_mode.v1.ToolCallCancelled
	(*Notification)(nil),                    // 16: codex.code_mode.v1.Notification
	(*NotificationCancelled)(nil),           // 17: codex.code_mode.v1.NotificationCancelled
	(*AcknowledgeNotificationRequest)(nil),  // 18: codex.code_mode.v1.AcknowledgeNotificationRequest
	(*AcknowledgeNotificationResponse)(nil), // 19: codex.code_mode.v1.AcknowledgeNotificationResponse
	(*CellClosed)(nil),                      // 20: codex.code_mode.v1.CellClosed
	(*ExecuteRequest)(nil),                  // 21: codex.code_mode.v1.ExecuteRequest
	(*ExecuteEvent)(nil),                    // 22: codex.code_mode.v1.ExecuteEvent
	(*ExecutionStarted)(nil),                // 23: codex.code_mode.v1.ExecutionStarted
	(*WaitRequest)(nil),                     // 24: codex.code_mode.v1.WaitRequest
	(*WaitResponse)(nil),                    // 25: codex.code_mode.v1.WaitResponse
	(*CancelWaitRequest)(nil),               // 26: codex.code_mode.v1.CancelWaitRequest
	(*CancelWaitResponse)(nil),              // 27: codex.code_mode.v1.CancelWaitResponse
	(*TerminateRequest)(nil),                // 28: codex.code_mode.v1.TerminateRequest
	(*ExecutionOutcome)(nil),                // 29: codex.code_mode.v1.ExecutionOutcome
	(*ExecutionYielded)(nil),                // 30: codex.code_mode.v1.ExecutionYielded
	(*ExecutionTerminated)(nil),             // 31: codex.code_mode.v1.ExecutionTerminated
	(*ExecutionCompleted)(nil),              // 32: codex.code_mode.v1.ExecutionCompleted
	(*ToolDefinition)(nil),                  // 33: codex.code_mode.v1.ToolDefinition
	(*ToolName)(nil),                        // 34: codex.code_mode.v1.ToolName
	(*ContentItem)(nil),                     // 35: codex.code_mode.v1.ContentItem
	(*TextContent)(nil),                     // 36: codex.code_mode.v1.TextContent
	(*ImageContent)(nil),                    // 37: codex.code_mode.v1.ImageContent
	(*AudioContent)(nil),                    // 38: codex.code_mode.v1.AudioContent
}
var file_codex_code_mode_v1_proto_depIdxs = []int32{
	4,  // 0: codex.code_mode.v1.OpenSessionRequest.cell_execution_limits:type_name -> codex.code_mode.v1.SessionCellExecutionLimits
	6,  // 1: codex.code_mode.v1.SessionEvent.opened:type_name -> codex.code_mode.v1.SessionOpened
	15, // 2: codex.code_mode.v1.SessionEvent.tool_call_cancelled:type_name -> codex.code_mode.v1.ToolCallCancelled
	16, // 3: codex.code_mode.v1.SessionEvent.notification:type_name -> codex.code_mode.v1.Notification
	17, // 4: codex.code_mode.v1.SessionEvent.notification_cancelled:type_name -> codex.code_mode.v1.NotificationCancelled
	20, // 5: codex.code_mode.v1.SessionEvent.cell_closed:type_name -> codex.code_mode.v1.CellClosed
	34, // 6: codex.code_mode.v1.SubscribeToToolCallsRequest.tool_names:type_name -> codex.code_mode.v1.ToolName
	34, // 7: codex.code_mode.v1.ToolCall.tool_name:type_name -> codex.code_mode.v1.ToolName
	0,  // 8: codex.code_mode.v1.ToolCall.tool_kind:type_name -> codex.code_mode.v1.ToolKind
	12, // 9: codex.code_mode.v1.CompleteToolCallRequest.succeeded:type_name -> codex.code_mode.v1.ToolCallSucceeded
	13, // 10: codex.code_mode.v1.CompleteToolCallRequest.failed:type_name -> codex.code_mode.v1.ToolCallFailed
	33, // 11: codex.code_mode.v1.ExecuteRequest.enabled_tools:type_name -> codex.code_mode.v1.ToolDefinition
	23, // 12: codex.code_mode.v1.ExecuteEvent.started:type_name -> codex.code_mode.v1.ExecutionStarted
	29, // 13: codex.code_mode.v1.ExecuteEvent.outcome:type_name -> codex.code_mode.v1.ExecutionOutcome
	29, // 14: codex.code_mode.v1.WaitResponse.live_cell:type_name -> codex.code_mode.v1.ExecutionOutcome
	29, // 15: codex.code_mode.v1.WaitResponse.missing_cell:type_name -> codex.code_mode.v1.ExecutionOutcome
	35, // 16: codex.code_mode.v1.ExecutionOutcome.content_items:type_name -> codex.code_mode.v1.ContentItem
	30, // 17: codex.code_mode.v1.ExecutionOutcome.yielded:type_name -> codex.code_mode.v1.ExecutionYielded
	31, // 18: codex.code_mode.v1.ExecutionOutcome.terminated:type_name -> codex.code_mode.v1.ExecutionTerminated
	32, // 19: codex.code_mode.v1.ExecutionOutcome.completed:type_name -> codex.code_mode.v1.ExecutionCompleted
	34, // 20: codex.code_mode.v1.ToolDefinition.tool_name:type_name -> codex.code_mode.v1.ToolName
	0,  // 21: codex.code_mode.v1.ToolDefinition.kind:type_name -> codex.code_mode.v1.ToolKind
	36, // 22: codex.code_mode.v1.ContentItem.text:type_name -> codex.code_mode.v1.TextContent
	37, // 23: codex.code_mode.v1.ContentItem.image:type_name -> codex.code_mode.v1.ImageContent
	38, // 24: codex.code_mode.v1.ContentItem.audio:type_name -> codex.code_mode.v1.AudioContent
	1,  // 25: codex.code_mode.v1.ImageContent.detail:type_name -> codex.code_mode.v1.ImageDetail
	2,  // 26: codex.code_mode.v1.CodeModeHost.Transport:input_type -> codex.code_mode.v1.FramedMessage
	3,  // 27: codex.code_mode.v1.CodeModeHost.OpenSession:input_type -> codex.code_mode.v1.OpenSessionRequest
	7,  // 28: codex.code_mode.v1.CodeModeHost.CloseSession:input_type -> codex.code_mode.v1.CloseSessionRequest
	9,  // 29: codex.code_mode.v1.CodeModeHost.SubscribeToToolCalls:input_type -> codex.code_mode.v1.SubscribeToToolCallsRequest
	11, // 30: codex.code_mode.v1.CodeModeHost.CompleteToolCall:input_type -> codex.code_mode.v1.CompleteToolCallRequest
	18, // 31: codex.code_mode.v1.CodeModeHost.AcknowledgeNotification:input_type -> codex.code_mode.v1.AcknowledgeNotificationRequest
	21, // 32: codex.code_mode.v1.CodeModeHost.Execute:input_type -> codex.code_mode.v1.ExecuteRequest
	24, // 33: codex.code_mode.v1.CodeModeHost.Wait:input_type -> codex.code_mode.v1.WaitRequest
	26, // 34: codex.code_mode.v1.CodeModeHost.CancelWait:input_type -> codex.code_mode.v1.CancelWaitRequest
	28, // 35: codex.code_mode.v1.CodeModeHost.Terminate:input_type -> codex.code_mode.v1.TerminateRequest
	2,  // 36: codex.code_mode.v1.CodeModeHost.Transport:output_type -> codex.code_mode.v1.FramedMessage
	5,  // 37: codex.code_mode.v1.CodeModeHost.OpenSession:output_type -> codex.code_mode.v1.SessionEvent
	8,  // 38: codex.code_mode.v1.CodeModeHost.CloseSession:output_type -> codex.code_mode.v1.CloseSessionResponse
	10, // 39: codex.code_mode.v1.CodeModeHost.SubscribeToToolCalls:output_type -> codex.code_mode.v1.ToolCall
	14, // 40: codex.code_mode.v1.CodeModeHost.CompleteToolCall:output_type -> codex.code_mode.v1.CompleteToolCallResponse
	19, // 41: codex.code_mode.v1.CodeModeHost.AcknowledgeNotification:output_type -> codex.code_mode.v1.AcknowledgeNotificationResponse
	22, // 42: codex.code_mode.v1.CodeModeHost.Execute:output_type -> codex.code_mode.v1.ExecuteEvent
	25, // 43: codex.code_mode.v1.CodeModeHost.Wait:output_type -> codex.code_mode.v1.WaitResponse
	27, // 44: codex.code_mode.v1.CodeModeHost.CancelWait:output_type -> codex.code_mode.v1.CancelWaitResponse
	25, // 45: codex.code_mode.v1.CodeModeHost.Terminate:output_type -> codex.code_mode.v1.WaitResponse
	36, // [36:46] is the sub-list for method output_type
	26, // [26:36] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_codex_code_mode_v1_proto_init() }
func file_codex_code_mode_v1_proto_init() {
	if File_codex_code_mode_v1_proto != nil {
		return
	}
	file_codex_code_mode_v1_proto_msgTypes[1].OneofWrappers = []any{}
	file_codex_code_mode_v1_proto_msgTypes[2].OneofWrappers = []any{}
	file_codex_code_mode_v1_proto_msgTypes[3].OneofWrappers = []any{
		(*SessionEvent_Opened)(nil),
		(*SessionEvent_ToolCallCancelled)(nil),
		(*SessionEvent_Notification)(nil),
		(*SessionEvent_NotificationCancelled)(nil),
		(*SessionEvent_CellClosed)(nil),
	}
	file_codex_code_mode_v1_proto_msgTypes[8].OneofWrappers = []any{}
	file_codex_code_mode_v1_proto_msgTypes[9].OneofWrappers = []any{
		(*CompleteToolCallRequest_Succeeded)(nil),
		(*CompleteToolCallRequest_Failed)(nil),
	}
	file_codex_code_mode_v1_proto_msgTypes[19].OneofWrappers = []any{}
	file_codex_code_mode_v1_proto_msgTypes[20].OneofWrappers = []any{
		(*ExecuteEvent_Started)(nil),
		(*ExecuteEvent_Outcome)(nil),
	}
	file_codex_code_mode_v1_proto_msgTypes[23].OneofWrappers = []any{
		(*WaitResponse_LiveCell)(nil),
		(*WaitResponse_MissingCell)(nil),
	}
	file_codex_code_mode_v1_proto_msgTypes[27].OneofWrappers = []any{
		(*ExecutionOutcome_Yielded)(nil),
		(*ExecutionOutcome_Terminated)(nil),
		(*ExecutionOutcome_Completed)(nil),
	}
	file_codex_code_mode_v1_proto_msgTypes[30].OneofWrappers = []any{}
	file_codex_code_mode_v1_proto_msgTypes[31].OneofWrappers = []any{}
	file_codex_code_mode_v1_proto_msgTypes[32].OneofWrappers = []any{}
	file_codex_code_mode_v1_proto_msgTypes[33].OneofWrappers = []any{
		(*ContentItem_Text)(nil),
		(*ContentItem_Image)(nil),
		(*ContentItem_Audio)(nil),
	}
	file_codex_code_mode_v1_proto_msgTypes[35].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codex_code_mode_v1_proto_rawDesc), len(file_codex_code_mode_v1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_codex_code_mode_v1_proto_goTypes,
		DependencyIndexes: file_codex_code_mode_v1_proto_depIdxs,
		EnumInfos:         file_codex_code_mode_v1_proto_enumTypes,
		MessageInfos:      file_codex_code_mode_v1_proto_msgTypes,
	}.Build()
	File_codex_code_mode_v1_proto = out.File
	file_codex_code_mode_v1_proto_goTypes = nil
	file_codex_code_mode_v1_proto_depIdxs = nil
}
