package agentboard

// Message-board records shared by backends and tool adapters.
//
// Rust parity: codex-rs/ext/agent-message-board/src/types.rs. IDs are strings on
// the Go side (the values are UUIDs generated by the board, or the host's
// thread identifiers).

import (
	"encoding/json"
	"errors"
	"time"

	"codex_go/agent"
)

// PostMetadata identifies one post or reply.
type PostMetadata struct {
	MessageID   string          `json:"message_id"`
	ChannelName string          `json:"channel_name"`
	Author      agent.AgentPath `json:"author"`
	ThreadID    string          `json:"thread_id"`
	CreatedAt   time.Time       `json:"created_at"`
}

// PostPreview is a truncated post rendering.
type PostPreview struct {
	PostMetadata
	TextPreview string `json:"text_preview"`
	NChars      int    `json:"n_chars"`
	Truncated   bool   `json:"truncated"`
}

// PostContent is one bounded post read.
type PostContent struct {
	PostMetadata
	Text            string `json:"text"`
	NChars          int    `json:"n_chars"`
	NextOffsetChars int    `json:"next_offset_chars"`
}

// ThreadSummary describes one discussion thread.
type ThreadSummary struct {
	ThreadID       string       `json:"thread_id"`
	RootPost       PostPreview  `json:"root_post"`
	ReplyCount     int          `json:"reply_count"`
	LastActivityAt time.Time    `json:"last_activity_at"`
	LatestReply    *PostPreview `json:"latest_reply"`
}

// ChannelSummary describes one channel.
type ChannelSummary struct {
	ChannelName   string          `json:"channel_name"`
	CreatedAt     time.Time       `json:"created_at"`
	CreatedBy     agent.AgentPath `json:"created_by"`
	MessageCount  int             `json:"message_count"`
	LastMessageID *string         `json:"last_message_id"`
}

// SubscriptionState is the resulting subscription after a change.
type SubscriptionState struct {
	ChannelName   string          `json:"channel_name"`
	ThreadID      *string         `json:"thread_id"`
	TargetAgent   agent.AgentPath `json:"target_agent"`
	Enabled       bool            `json:"enabled"`
	LastMessageID *string         `json:"last_message_id"`
}

// Page is a bounded page of results. Counts and the end-of-list marker are
// derived at serialization (Rust's Page<T> Serialize impl).
type Page[T any] struct {
	Results    []T
	NextCursor *string
}

// MarshalJSON mirrors Rust's Page serialization: results, n_returned, has_more
// and next_cursor.
func (p Page[T]) MarshalJSON() ([]byte, error) {
	payload := struct {
		Results    []T     `json:"results"`
		NReturned  int     `json:"n_returned"`
		HasMore    bool    `json:"has_more"`
		NextCursor *string `json:"next_cursor"`
	}{
		Results:    p.Results,
		NReturned:  len(p.Results),
		HasMore:    p.NextCursor != nil,
		NextCursor: p.NextCursor,
	}
	return json.Marshal(payload)
}

// UnmarshalJSON reads Rust's Page form: the results and an optional cursor. The
// derived counts are ignored, exactly like deserializing into `results` plus
// `next_cursor`.
func (p *Page[T]) UnmarshalJSON(data []byte) error {
	if p == nil {
		return errors.New("page target is nil")
	}
	var payload struct {
		Results    []T     `json:"results"`
		NextCursor *string `json:"next_cursor"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		return err
	}
	p.Results = payload.Results
	p.NextCursor = payload.NextCursor
	return nil
}

// ThreadPage is one page of a thread: the root post plus a page of replies.
//
// Its JSON form is Rust's flattened `ThreadPage` (`root_post` beside the reply
// page's own fields), which is what a host receives from the board service and
// what the board tools return.
type ThreadPage struct {
	RootPost PostPreview
	Replies  Page[PostPreview]
}

func (p ThreadPage) MarshalJSON() ([]byte, error) {
	payload := struct {
		RootPost   PostPreview   `json:"root_post"`
		Results    []PostPreview `json:"results"`
		NReturned  int           `json:"n_returned"`
		HasMore    bool          `json:"has_more"`
		NextCursor *string       `json:"next_cursor"`
	}{
		RootPost:   p.RootPost,
		Results:    p.Replies.Results,
		NReturned:  len(p.Replies.Results),
		HasMore:    p.Replies.NextCursor != nil,
		NextCursor: p.Replies.NextCursor,
	}
	if payload.Results == nil {
		payload.Results = []PostPreview{}
	}
	return json.Marshal(payload)
}

func (p *ThreadPage) UnmarshalJSON(data []byte) error {
	if p == nil {
		return errors.New("thread page target is nil")
	}
	var payload struct {
		RootPost   PostPreview   `json:"root_post"`
		Results    []PostPreview `json:"results"`
		NextCursor *string       `json:"next_cursor"`
	}
	if err := json.Unmarshal(data, &payload); err != nil {
		return err
	}
	p.RootPost = payload.RootPost
	p.Replies = Page[PostPreview]{Results: payload.Results, NextCursor: payload.NextCursor}
	return nil
}
