package agentboard

// Message-board records shared by backends and tool adapters.
//
// Rust parity: codex-rs/ext/agent-message-board/src/types.rs. IDs are strings on
// the Go side (the values are UUIDs generated by the board, or the host's
// thread identifiers).

import (
	"encoding/json"
	"time"

	"codex_go/agent"
)

// PostMetadata identifies one post or reply.
type PostMetadata struct {
	MessageID   string          `json:"message_id"`
	ChannelName string          `json:"channel_name"`
	Author      agent.AgentPath `json:"author"`
	ThreadID    string          `json:"thread_id"`
	CreatedAt   time.Time       `json:"created_at"`
}

// PostPreview is a truncated post rendering.
type PostPreview struct {
	PostMetadata
	TextPreview string `json:"text_preview"`
	NChars      int    `json:"n_chars"`
	Truncated   bool   `json:"truncated"`
}

// PostContent is one bounded post read.
type PostContent struct {
	PostMetadata
	Text            string `json:"text"`
	NChars          int    `json:"n_chars"`
	NextOffsetChars int    `json:"next_offset_chars"`
}

// ThreadSummary describes one discussion thread.
type ThreadSummary struct {
	ThreadID       string       `json:"thread_id"`
	RootPost       PostPreview  `json:"root_post"`
	ReplyCount     int          `json:"reply_count"`
	LastActivityAt time.Time    `json:"last_activity_at"`
	LatestReply    *PostPreview `json:"latest_reply"`
}

// ChannelSummary describes one channel.
type ChannelSummary struct {
	ChannelName   string          `json:"channel_name"`
	CreatedAt     time.Time       `json:"created_at"`
	CreatedBy     agent.AgentPath `json:"created_by"`
	MessageCount  int             `json:"message_count"`
	LastMessageID *string         `json:"last_message_id"`
}

// SubscriptionState is the resulting subscription after a change.
type SubscriptionState struct {
	ChannelName   string          `json:"channel_name"`
	ThreadID      *string         `json:"thread_id"`
	TargetAgent   agent.AgentPath `json:"target_agent"`
	Enabled       bool            `json:"enabled"`
	LastMessageID *string         `json:"last_message_id"`
}

// Page is a bounded page of results. Counts and the end-of-list marker are
// derived at serialization (Rust's Page<T> Serialize impl).
type Page[T any] struct {
	Results    []T
	NextCursor *string
}

// MarshalJSON mirrors Rust's Page serialization: results, n_returned, has_more
// and next_cursor.
func (p Page[T]) MarshalJSON() ([]byte, error) {
	payload := struct {
		Results    []T     `json:"results"`
		NReturned  int     `json:"n_returned"`
		HasMore    bool    `json:"has_more"`
		NextCursor *string `json:"next_cursor"`
	}{
		Results:    p.Results,
		NReturned:  len(p.Results),
		HasMore:    p.NextCursor != nil,
		NextCursor: p.NextCursor,
	}
	return json.Marshal(payload)
}

// ThreadPage is one page of a thread: the root post plus a page of replies.
type ThreadPage struct {
	RootPost PostPreview       `json:"root_post"`
	Replies  Page[PostPreview] `json:"replies"`
}
