package historycell

import "math/rand/v2"

// Rust parity: codex-rs/tui/src/empty_state_animation/greetings.rs. Startup
// phrases retained from the approved greeting list (PR #10248). One selection
// is shared by the provisional, live, and committed session headers.

// Greetings is the approved startup greeting catalog.
var Greetings = []string{
	"Whoa, fancy meeting you here!",
	"Look who\u2019s at the keyboard.",
	"Hello, you. Got an idea?",
	"Nice to see you in these parts.",
	"Pull up a prompt.",
	"What brings you to this corner of the terminal?",
	"Hey there. Big plans or little fixes?",
	"What are we getting into today?",
	"Got something you want to try?",
	"What\u2019s today\u2019s little adventure?",
	"Anything interesting on the docket?",
	"Take your time. The cursor can wait.",
	"A half-formed idea will do.",
	"Come on in. There\u2019s room for an idea.",
	"You, me, and a blinking cursor.",
	"It takes two to tango. What\u2019s our first step?",
	"You bring the idea. I\u2019ll bring the brackets.",
	"Your move, teammate.",
	"What are we cooking up?",
	"Shall we turn \u201cwhat if\u201d into something?",
	"What\u2019s the first thing on our napkin sketch?",
	"Bring your unfinished thoughts.",
	"You set the direction. We\u2019ll work out the steps.",
	"Ah, the terminal. A classic meeting spot.",
	"Nice place you\u2019ve got here. Very monospace.",
	"Welcome to our little rectangle of possibility.",
	"A cursor blinks. The plot thickens.",
	"The prompt is yours.",
	"Fancy a little quality terminal time?",
	"How\u2019s life between the brackets?",
	"Shall we give this cursor a purpose?",
	"A fresh prompt. An open question.",
	"Your keyboard has entered the chat.",
	"Hello, world. Hello, you.",
	"Welcome to the blinking edge of possibility.",
	"Any loose ends? Semicolons count.",
	"Shall we make this terminal earn its keep?",
	"Got an itch to fix a thing?",
	"Show me the bit that\u2019s being weird.",
	"Greetings, fellow tinkerer.",
	"Well, well, well. An idea approaches.",
	"What\u2019s today\u2019s side quest?",
	"Is this a plan day or a poke-around day?",
	"Practical, peculiar, or a little of both?",
	"Rough sketches welcome.",
	"Shall we see where this goes?",
	"All right. What have you got?",
	"Back for another round?",
	"Same terminal, new possibilities.",
	"Welcome back. Familiar territory or a fresh adventure?",
	"Follow the white cursor.",
	"Welcome to the command line, Neo.",
	"A glitch in the Matrix, or just a missing semicolon?",
	"How deep does this codebase go?",
	"Speak, friend, and enter a prompt.",
	"One prompt to begin the journey.",
	"May the source be with you.",
	"These might be the bugs you\u2019re looking for.",
	"A new prompt awakens.",
	"Forty-two is an answer. What\u2019s the question?",
	"It\u2019s dangerous to code alone. Take a prompt.",
	"The code must flow.",
	"You rang? Metaphorically. You typed.",
	"Hello again, carbon-based collaborator.",
	"This looks like the start of a perfectly reasonable rabbit hole.",
	"Shall we turn \u201chuh?\u201d into \u201caha!\u201d?",
	"Well, this terminal just got interesting.",
	"The source is strong with this one.",
	"There\u2019s a perfectly good prompt with your name on it.",
	"Here for a quick fix or the extended edition?",
	"What\u2019s the latest from your side of the keyboard?",
	"Got a minute and a mildly unreasonable idea?",
	"A hunch is a perfectly respectable starting point.",
	"Hello again. What\u2019s the plot this time?",
	"Shall we make a little something out of nothing?",
	"Welcome to the neighborhood. Lots of characters here.",
	"Nice terminal. Does it come in widescreen?",
	"Your cursor called. It wants a plot.",
	"Shall we put some verbs after that cursor?",
	"Welcome. There\u2019s no dress code, just code.",
	"This terminal has excellent conversational potential.",
	"Got an idea that won\u2019t stay on the napkin?",
	"What are we building in this episode?",
	"Bring a question. Bonus points if it\u2019s a weird one.",
	"What are we poking with a metaphorical stick?",
	"Shall we make the thing that makes the other thing easier?",
	"Welcome to the part where the idea gets interesting.",
	"A long time ago, in a directory not so far away\u2026",
}

// ChooseGreeting selects one approved greeting.
func ChooseGreeting() string {
	return Greetings[rand.IntN(len(Greetings))]
}
