package recordreplay

// Core-level replay: drives the Rust-recorded session through Go's actual
// app-server core (RuntimeRouter + turn runtime), token-free. This is the
// dynamic half of djalign method 2: instead of only replaying the task
// lifecycle through the storage recorder (rollout.Recorder), the recording is
// fed into the full app-server turn pipeline with a scripted agent that
// reproduces the recorded per-task item surface (reasoning presence and agent
// message presence). The observable contract - notification stream and
// persisted paginated rollout - is then compared against the recording.

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"codex_go/appserver"
	"codex_go/model"
	"codex_go/rollout"
	"codex_go/session"
	"codex_go/turn"
)

// CoreNotification is one app-server notification in the observable stream.
// Volatile fields (timestamps, ids generated by the runtime) are not part of
// the contract; only method, turn association, item type and text presence
// are kept.
type CoreNotification struct {
	Method   string `json:"method"`              // turn/started | item/started | item/completed | turn/completed
	TurnID   string `json:"turn_id,omitempty"`   // runtime-generated turn id
	ItemType string `json:"item_type,omitempty"` // normalized item wire type
	HasText  bool   `json:"has_text,omitempty"`  // presence of item text
	Status   string `json:"status,omitempty"`    // for turn/completed
}

// PersistedLine is one normalized line of the persisted paginated rollout.
type PersistedLine struct {
	Type     string `json:"type"`              // session_meta | task_started | item_started | item_completed | task_complete
	TurnID   string `json:"turn_id,omitempty"` // turn id carried by the line
	ItemType string `json:"item_type,omitempty"`
	Ordinal  uint64 `json:"ordinal"`
}

// CoreReplayResult is the observable contract produced by replaying a
// recording through Go's app-server core.
type CoreReplayResult struct {
	ThreadID      string             `json:"thread_id"`
	TurnIDs       []string           `json:"turn_ids"` // one per recorded task, in order
	RolloutPath   string             `json:"rollout_path"`
	Notifications []CoreNotification `json:"notifications"`
	Persisted     []PersistedLine    `json:"persisted"`
}

// coreReplayAgent is a scripted model.AgentRunner that reproduces the
// recording's per-task item surface: for task i it returns a reasoning item
// (presence) and an agent message item (presence) exactly when the recording
// has reasoning deltas / an agent message for that task. Model text is
// replaced by a fixed placeholder - text is explicitly out of contract.
type coreReplayAgent struct {
	lifecycles []TaskLifecycle
	mu         sync.Mutex
	calls      int
}

func newCoreReplayAgent(lifecycles []TaskLifecycle) *coreReplayAgent {
	return &coreReplayAgent{lifecycles: lifecycles}
}

func (a *coreReplayAgent) Run(_ context.Context, request *model.AgentRequest) (*model.AgentResponse, error) {
	if a == nil {
		return nil, errors.New("core replay agent is nil")
	}
	a.mu.Lock()
	index := a.calls
	a.calls++
	a.mu.Unlock()
	if index >= len(a.lifecycles) {
		index = len(a.lifecycles) - 1
	}
	lc := a.lifecycles[index]
	hasReasoning := false
	hasMessage := false
	for _, msgType := range lc.MsgTypes {
		if strings.Contains(msgType, "reasoning") {
			hasReasoning = true
		}
		if msgType == "agent_message" || msgType == "message" {
			hasMessage = true
		}
	}
	items := make([]model.AgentItem, 0, 2)
	if hasReasoning {
		items = append(items, model.AgentItem{
			ID:   "reasoning-" + lc.ID,
			Type: "reasoning",
			Text: "<reasoning text omitted from contract>",
		})
	}
	if hasMessage {
		items = append(items, model.AgentItem{
			ID:   "message-" + lc.ID,
			Type: "agent_message",
			Text: "<message text omitted from contract>",
		})
	}
	return &model.AgentResponse{
		ResponseID: "resp-" + lc.ID,
		Message:    "<message text omitted from contract>",
		Usage:      model.AgentUsage{InputTokens: 10, OutputTokens: 5, TotalTokens: 15},
		Items:      items,
		Model:      request.Model,
		ProviderID: request.ProviderID,
	}, nil
}

// ReplayThroughCore drives the recording's task lifecycles through Go's
// app-server core: one thread is started (paginated history), and one turn is
// run per recorded task with a scripted agent reproducing the recording's
// item surface. The notification stream and the persisted rollout are
// captured for contract comparison. It never calls a model provider.
func ReplayThroughCore(events []Event, codexHome string) (*CoreReplayResult, error) {
	lifecycles := TaskLifecycles(events)
	if len(lifecycles) == 0 {
		return nil, errors.New("recording has no task lifecycles to replay")
	}
	if strings.TrimSpace(codexHome) == "" {
		return nil, errors.New("codex home is required")
	}
	workspace := filepath.Join(codexHome, "workspace")
	if err := os.MkdirAll(workspace, 0o755); err != nil {
		return nil, fmt.Errorf("create replay workspace: %w", err)
	}
	store := session.NewStore(codexHome)
	sink := appserver.NewNotificationBuffer()
	router := appserver.NewRuntimeRouter(appserver.RuntimeServices{
		ThreadRouter: appserver.NewRouter(store),
		Turns:        turn.NewTurnService(),
		Agent:        newCoreReplayAgent(lifecycles),
		ThreadStatus: appserver.NewThreadStatusManager(),
	})
	defer func() {
		_ = router.Close()
	}()
	router.SetNotificationSink(sink)

	start := router.Handle(&appserver.Request{
		ID:     appserver.IntID(1),
		Method: appserver.MethodThreadStart,
		Params: mustMarshalParams(appserver.ThreadStartParams{
			CWD:         workspace,
			HistoryMode: appserver.ThreadHistoryPaginated,
		}),
	})
	if start.Error != nil {
		return nil, fmt.Errorf("thread/start: %v", start.Error)
	}
	threadID := start.Result.(*appserver.ThreadStartResponse).Thread.ID

	result := &CoreReplayResult{ThreadID: threadID}
	for i := range lifecycles {
		response := router.Handle(&appserver.Request{
			ID:     appserver.IntID(int64(i) + 2),
			Method: appserver.MethodTurnStart,
			Params: mustMarshalParams(turn.TurnStartParams{ThreadID: threadID}),
		})
		if response.Error != nil {
			return nil, fmt.Errorf("turn/start task %d: %v", i, response.Error)
		}
		turnID := response.Result.(*turn.TurnStartResponse).Turn.ID
		completed, err := waitForCoreTurnCompleted(sink, turnID, 30*time.Second)
		if err != nil {
			return nil, fmt.Errorf("task %d (turn %s): %w", i, turnID, err)
		}
		if completed != nil {
			result.TurnIDs = append(result.TurnIDs, turnID)
		}
	}
	for _, notification := range sink.List() {
		result.Notifications = append(result.Notifications, normalizeCoreNotification(notification))
	}
	path, err := rollout.FindThreadPath(codexHome, threadID, false)
	if err != nil {
		return nil, fmt.Errorf("locate persisted replay rollout: %w", err)
	}
	result.RolloutPath = path
	result.Persisted, err = persistedCoreLines(path)
	if err != nil {
		return nil, err
	}
	return result, nil
}

func mustMarshalParams(value any) json.RawMessage {
	data, err := json.Marshal(value)
	if err != nil {
		return json.RawMessage("{}")
	}
	return data
}

// waitForCoreTurnCompleted polls the notification buffer until the matching
// turn/completed notification reports the completed status.
func waitForCoreTurnCompleted(sink *appserver.NotificationBuffer, turnID string, timeout time.Duration) (*appserver.TurnCompletedNotification, error) {
	deadline := time.Now().Add(timeout)
	var last []*appserver.Notification
	for time.Now().Before(deadline) {
		last = sink.List()
		for _, notification := range last {
			if notification == nil || notification.Method != appserver.NotificationTurnCompleted {
				continue
			}
			completed, ok := notification.Params.(*appserver.TurnCompletedNotification)
			if !ok || completed == nil || completed.Turn.ID != turnID {
				continue
			}
			if completed.Turn.Status == appserver.TurnStatusCompleted {
				return completed, nil
			}
			return nil, fmt.Errorf("turn %s completed with status %q", turnID, completed.Turn.Status)
		}
		time.Sleep(10 * time.Millisecond)
	}
	return nil, fmt.Errorf("timed out waiting for turn %s completion in %#v", turnID, last)
}

// normalizeCoreNotification keeps only the observable contract fields.
func normalizeCoreNotification(notification *appserver.Notification) CoreNotification {
	if notification == nil {
		return CoreNotification{}
	}
	out := CoreNotification{Method: string(notification.Method)}
	switch typed := notification.Params.(type) {
	case *appserver.TurnStartedNotification:
		if typed != nil {
			out.TurnID = typed.Turn.ID
		}
	case *appserver.TurnCompletedNotification:
		if typed != nil {
			out.TurnID = typed.Turn.ID
			out.Status = string(typed.Turn.Status)
		}
	case *appserver.ItemStartedNotification:
		if typed != nil {
			out.TurnID = typed.TurnID
			out.ItemType = normalizedItemWireType(typed.Item)
			out.HasText = itemPayloadHasText(typed.Item)
		}
	case *appserver.ItemCompletedNotification:
		if typed != nil {
			out.TurnID = typed.TurnID
			out.ItemType = normalizedItemWireType(typed.Item)
			out.HasText = itemPayloadHasText(typed.Item)
		}
	}
	return out
}

func normalizedItemWireType(payload appserver.ThreadItemPayload) string {
	if payload == nil {
		return ""
	}
	value, _ := payload["type"].(string)
	return normalizeItemType(value)
}

// normalizeItemType maps the app-server wire and paginated core kind spellings
// to one canonical token used by the cross-check. Both spellings are produced
// by Go's runtime: the notification payload carries the camelCase wire type
// (agentMessage) while the persisted paginated rollout carries the Rust
// protocol TurnItem kind (AgentMessage).
func normalizeItemType(value string) string {
	switch strings.TrimSpace(value) {
	case "agent_message", "agentMessage", "AgentMessage", "assistant_message":
		return "agent_message"
	case "reasoning", "Reasoning":
		return "reasoning"
	default:
		return strings.TrimSpace(value)
	}
}

func itemPayloadHasText(payload appserver.ThreadItemPayload) bool {
	if payload == nil {
		return false
	}
	text, _ := payload["text"].(string)
	return strings.TrimSpace(text) != ""
}

// persistedCoreLines normalizes the persisted rollout into the observable
// line sequence: session_meta first, then per turn task_started /
// item_started / item_completed / task_complete, with contiguous ordinals.
func persistedCoreLines(path string) ([]PersistedLine, error) {
	lines, _, err := rollout.Load(path)
	if err != nil {
		return nil, fmt.Errorf("load persisted replay rollout: %w", err)
	}
	out := make([]PersistedLine, 0, len(lines))
	for _, line := range lines {
		switch line.Type {
		case "session_meta":
			entry := PersistedLine{Type: "session_meta"}
			if line.Ordinal != nil {
				entry.Ordinal = *line.Ordinal
			}
			out = append(out, entry)
		case "event_msg":
			var payload struct {
				Type   string          `json:"type"`
				TurnID string          `json:"turn_id"`
				Item   json.RawMessage `json:"item"`
			}
			if err := json.Unmarshal(line.Payload, &payload); err != nil {
				continue
			}
			entry := PersistedLine{Type: payload.Type, TurnID: payload.TurnID}
			if line.Ordinal != nil {
				entry.Ordinal = *line.Ordinal
			}
			if len(payload.Item) > 0 && (payload.Type == "item_started" || payload.Type == "item_completed") {
				var item struct {
					Type string `json:"type"`
				}
				if json.Unmarshal(payload.Item, &item) == nil {
					entry.ItemType = item.Type
				}
			}
			out = append(out, entry)
		}
	}
	return out, nil
}

// ValidateCoreReplayCrossCheck verifies that the core replay reproduces the
// recording's observable contract: the same number of tasks in the same
// order, each completed; per-task reasoning presence and agent message
// presence in the notification stream; and a persisted paginated rollout with
// session_meta first, contiguous ordinals and the canonical
// task_started/item/task_complete lifecycle per turn.
func ValidateCoreReplayCrossCheck(events []Event, result *CoreReplayResult) error {
	if result == nil {
		return errors.New("core replay result is nil")
	}
	lifecycles := TaskLifecycles(events)
	if len(lifecycles) == 0 {
		return errors.New("recording has no task lifecycles")
	}
	if len(result.TurnIDs) != len(lifecycles) {
		return fmt.Errorf("completed turns = %d, want %d (recorded tasks)", len(result.TurnIDs), len(lifecycles))
	}
	for i := range lifecycles {
		turnID := result.TurnIDs[i]
		lc := lifecycles[i]
		var sawStarted, sawCompleted bool
		var reasoning, message bool
		for _, notification := range result.Notifications {
			if notification.TurnID != turnID {
				continue
			}
			switch notification.Method {
			case "turn/started":
				sawStarted = true
			case "turn/completed":
				sawCompleted = notification.Status == string(appserver.TurnStatusCompleted)
			case "item/completed":
				if normalizeItemType(notification.ItemType) == "reasoning" {
					reasoning = true
				}
				if normalizeItemType(notification.ItemType) == "agent_message" && notification.HasText {
					message = true
				}
			}
		}
		if !sawStarted {
			return fmt.Errorf("task %s: missing turn/started notification for turn %s", lc.ID, turnID)
		}
		if !sawCompleted {
			return fmt.Errorf("task %s: turn %s did not complete with status completed", lc.ID, turnID)
		}
		recHasReasoning := lifecycleHasMsgType(lc, func(value string) bool { return strings.Contains(value, "reasoning") })
		if recHasReasoning && !reasoning {
			return fmt.Errorf("task %s: recording has reasoning but replay emitted no reasoning item/completed", lc.ID)
		}
		recHasMessage := lifecycleHasMsgType(lc, func(value string) bool { return value == "agent_message" || value == "message" })
		if recHasMessage && !message {
			return fmt.Errorf("task %s: recording has agent_message but replay emitted no agent_message item/completed", lc.ID)
		}
	}
	return validatePersistedCoreLifecycle(result.Persisted, len(lifecycles))
}

func lifecycleHasMsgType(lc TaskLifecycle, predicate func(string) bool) bool {
	for _, msgType := range lc.MsgTypes {
		if predicate(msgType) {
			return true
		}
	}
	return false
}

func validatePersistedCoreLifecycle(persisted []PersistedLine, taskCount int) error {
	if len(persisted) == 0 {
		return errors.New("persisted rollout is empty")
	}
	if persisted[0].Type != "session_meta" {
		return fmt.Errorf("persisted first line = %q, want session_meta", persisted[0].Type)
	}
	expectedOrdinal := uint64(0)
	perTurn := [][]string{}
	current := []string{}
	for _, line := range persisted {
		if line.Ordinal != expectedOrdinal {
			return fmt.Errorf("ordinal %d = %q (turn %s), want contiguous %d", line.Ordinal, line.Type, line.TurnID, expectedOrdinal)
		}
		expectedOrdinal++
		switch line.Type {
		case "session_meta":
			// first line only
		case "task_started":
			if len(current) > 0 {
				perTurn = append(perTurn, current)
			}
			current = []string{"task_started"}
		case "item_started", "item_completed":
			current = append(current, line.Type)
		case "task_complete":
			current = append(current, "task_complete")
			perTurn = append(perTurn, current)
			current = []string{}
		}
	}
	if len(current) > 0 {
		perTurn = append(perTurn, current)
	}
	if len(perTurn) != taskCount {
		return fmt.Errorf("persisted turns = %d, want %d", len(perTurn), taskCount)
	}
	for i, turnLines := range perTurn {
		if len(turnLines) < 3 {
			return fmt.Errorf("persisted turn %d has %d lines: %v", i, len(turnLines), turnLines)
		}
		if turnLines[0] != "task_started" {
			return fmt.Errorf("persisted turn %d starts with %q, want task_started", i, turnLines[0])
		}
		if turnLines[len(turnLines)-1] != "task_complete" {
			return fmt.Errorf("persisted turn %d ends with %q, want task_complete", i, turnLines[len(turnLines)-1])
		}
		for _, lineType := range turnLines[1 : len(turnLines)-1] {
			if lineType != "item_started" && lineType != "item_completed" {
				return fmt.Errorf("persisted turn %d unexpected line %q in body", i, lineType)
			}
		}
	}
	return nil
}
