package memories

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

const (
	WorkspaceDiffFilename = "phase2_workspace_diff.md"
	WorkspaceDiffMaxBytes = 4 * 1024 * 1024
	baselineCommitMessage = "Initialize Codex git baseline\n\nCo-authored-by: Codex <noreply@openai.com>"
)

type GitBaselineChangeStatus string

const (
	GitBaselineAdded    GitBaselineChangeStatus = "A"
	GitBaselineModified GitBaselineChangeStatus = "M"
	GitBaselineDeleted  GitBaselineChangeStatus = "D"
)

type GitBaselineChange struct {
	Status GitBaselineChangeStatus
	Path   string
}

type GitBaselineDiff struct {
	Changes     []GitBaselineChange
	UnifiedDiff string
}

func (d GitBaselineDiff) HasChanges() bool {
	return len(d.Changes) > 0
}

func PrepareWorkspace(ctx context.Context, root string) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := os.MkdirAll(root, 0o755); err != nil {
		return fmt.Errorf("create memory workspace %s: %w", root, err)
	}
	if err := removeMemorySymlinks(root); err != nil {
		return err
	}
	if err := removeWorkspaceDiff(root); err != nil {
		return err
	}
	if baselineUsable(ctx, root) {
		return nil
	}
	return resetGitBaseline(ctx, root)
}

// removeMemorySymlinks recursively removes symbolic links so a memory
// workspace cannot redirect writes (or reads) outside the workspace, and
// rejects a symlinked memory root (Rust #39205).
func removeMemorySymlinks(root string) error {
	root = filepath.Clean(root)
	if info, err := os.Lstat(root); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	} else if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("memory root cannot be a symbolic link: %s", root)
	}
	return filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if path == root {
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			return os.Remove(path)
		}
		return nil
	})
}

func WorkspaceDiff(ctx context.Context, root string) (GitBaselineDiff, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := removeWorkspaceDiff(root); err != nil {
		return GitBaselineDiff{}, err
	}
	if !baselineUsable(ctx, root) {
		return GitBaselineDiff{}, fmt.Errorf("open git repo %s: unusable memory baseline", root)
	}
	changes, err := listBaselineChanges(ctx, root)
	if err != nil {
		return GitBaselineDiff{}, err
	}
	var unified strings.Builder
	for _, change := range changes {
		section, err := renderBaselineChange(ctx, root, change)
		if err != nil {
			return GitBaselineDiff{}, err
		}
		unified.WriteString(section)
	}
	return GitBaselineDiff{Changes: changes, UnifiedDiff: unified.String()}, nil
}

func WriteWorkspaceDiff(root string, diff GitBaselineDiff) error {
	path := filepath.Join(root, WorkspaceDiffFilename)
	if err := os.WriteFile(path, []byte(RenderWorkspaceDiff(diff)), 0o666); err != nil {
		return fmt.Errorf("write memory workspace diff file %s: %w", path, err)
	}
	return nil
}

func ResetWorkspaceBaseline(ctx context.Context, root string) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := removeWorkspaceDiff(root); err != nil {
		return err
	}
	return resetGitBaseline(ctx, root)
}

func ValidateConsolidationArtifacts(root string) error {
	memoryPath := filepath.Join(root, MemoryFilename)
	info, err := os.Stat(memoryPath)
	if err != nil {
		return fmt.Errorf("read consolidated memory artifact %s: %w", memoryPath, err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("consolidated memory artifact is not a file: %s", memoryPath)
	}
	summaryPath := filepath.Join(root, MemorySummaryFilename)
	summary, err := os.ReadFile(summaryPath)
	if err != nil {
		return fmt.Errorf("read memory summary artifact %s: %w", summaryPath, err)
	}
	firstLine := string(summary)
	if index := strings.IndexByte(firstLine, '\n'); index >= 0 {
		firstLine = strings.TrimSuffix(firstLine[:index], "\r")
	}
	if firstLine != "v1" {
		return fmt.Errorf("memory summary artifact does not start with v1: %s", summaryPath)
	}
	return nil
}

func RenderWorkspaceDiff(diff GitBaselineDiff) string {
	var rendered strings.Builder
	rendered.WriteString("# Memory Workspace Diff\n\n")
	rendered.WriteString("Generated by Codex before Phase 2 memory consolidation. Read this file first and do not edit it.\n\n")
	rendered.WriteString("## Status\n")
	if !diff.HasChanges() {
		rendered.WriteString("- none\n")
		return rendered.String()
	}
	for _, change := range diff.Changes {
		fmt.Fprintf(&rendered, "- %s %s\n", change.Status, change.Path)
	}
	rendered.WriteString("\n## Diff\n\n```diff\n")
	appendBoundedWorkspaceDiff(&rendered, diff.UnifiedDiff)
	rendered.WriteString("```\n")
	return rendered.String()
}

func resetGitBaseline(ctx context.Context, root string) error {
	if err := os.MkdirAll(root, 0o755); err != nil {
		return fmt.Errorf("create git baseline root %s: %w", root, err)
	}
	gitPath := filepath.Join(root, ".git")
	if info, err := os.Lstat(gitPath); err == nil {
		if info.IsDir() && info.Mode()&os.ModeSymlink == 0 {
			if err := os.RemoveAll(gitPath); err != nil {
				return fmt.Errorf("remove %s: %w", gitPath, err)
			}
		} else if err := os.Remove(gitPath); err != nil {
			return fmt.Errorf("remove %s: %w", gitPath, err)
		}
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", gitPath, err)
	}
	if _, err := runBaselineGit(ctx, root, "init", "--quiet"); err != nil {
		return fmt.Errorf("init git repo %s: %w", root, err)
	}
	if _, err := runBaselineGit(ctx, root, "add", "--all", "--force"); err != nil {
		return fmt.Errorf("stage git baseline %s: %w", root, err)
	}
	if _, err := runBaselineGit(ctx, root,
		"-c", "user.name=Codex", "-c", "user.email=noreply@openai.com",
		"commit", "--quiet", "--allow-empty", "--no-gpg-sign", "--no-verify", "-m", baselineCommitMessage,
	); err != nil {
		return fmt.Errorf("commit git baseline repo %s: %w", root, err)
	}
	return nil
}

func baselineUsable(ctx context.Context, root string) bool {
	info, err := os.Stat(filepath.Join(root, ".git"))
	if err != nil || !info.IsDir() {
		return false
	}
	_, err = runBaselineGit(ctx, root, "rev-parse", "--verify", "HEAD^{tree}")
	return err == nil
}

func listBaselineChanges(ctx context.Context, root string) ([]GitBaselineChange, error) {
	tracked, err := runBaselineGit(ctx, root, "diff", "--name-status", "--no-renames", "-z", "HEAD", "--")
	if err != nil {
		return nil, fmt.Errorf("scan tracked memory workspace changes: %w", err)
	}
	byPath := map[string]GitBaselineChangeStatus{}
	parts := splitNUL(tracked)
	for index := 0; index+1 < len(parts); index += 2 {
		status := string(parts[index])
		path := filepath.ToSlash(string(parts[index+1]))
		switch {
		case strings.HasPrefix(status, "D"):
			byPath[path] = GitBaselineDeleted
		case strings.HasPrefix(status, "A"):
			byPath[path] = GitBaselineAdded
		default:
			byPath[path] = GitBaselineModified
		}
	}
	untracked, err := runBaselineGit(ctx, root, "ls-files", "--others", "--full-name", "-z")
	if err != nil {
		return nil, fmt.Errorf("scan untracked memory workspace files: %w", err)
	}
	for _, value := range splitNUL(untracked) {
		path := filepath.ToSlash(string(value))
		if path != "" {
			byPath[path] = GitBaselineAdded
		}
	}
	changes := make([]GitBaselineChange, 0, len(byPath))
	for path, status := range byPath {
		changes = append(changes, GitBaselineChange{Status: status, Path: path})
	}
	sort.Slice(changes, func(i, j int) bool { return changes[i].Path < changes[j].Path })
	return changes, nil
}

func renderBaselineChange(ctx context.Context, root string, change GitBaselineChange) (string, error) {
	if change.Status == GitBaselineAdded {
		data, mode, err := readWorkspaceEntry(filepath.Join(root, filepath.FromSlash(change.Path)))
		if err != nil {
			return "", fmt.Errorf("read current content for %s: %w", change.Path, err)
		}
		return renderAddedFileDiff(change.Path, mode, data), nil
	}
	data, err := runBaselineGit(ctx, root,
		"-c", "core.quotePath=false", "diff", "--no-ext-diff", "--no-textconv", "--no-renames", "--unified=3", "HEAD", "--", change.Path,
	)
	if err != nil {
		return "", fmt.Errorf("render memory workspace diff for %s: %w", change.Path, err)
	}
	return normalizeGitDiff(data), nil
}

func renderAddedFileDiff(path, mode string, data []byte) string {
	text := strings.ToValidUTF8(string(data), "\uFFFD")
	var rendered strings.Builder
	fmt.Fprintf(&rendered, "diff --git a/%s b/%s\n", path, path)
	fmt.Fprintf(&rendered, "new file mode %s\n", mode)
	fmt.Fprintf(&rendered, "--- /dev/null\n+++ b/%s\n", path)
	if len(text) == 0 {
		return rendered.String()
	}
	lines := strings.SplitAfter(text, "\n")
	if lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	if len(lines) == 1 {
		rendered.WriteString("@@ -0,0 +1 @@\n")
	} else {
		fmt.Fprintf(&rendered, "@@ -0,0 +1,%d @@\n", len(lines))
	}
	for _, line := range lines {
		rendered.WriteByte('+')
		rendered.WriteString(line)
		if !strings.HasSuffix(line, "\n") {
			rendered.WriteByte('\n')
		}
	}
	return rendered.String()
}

func normalizeGitDiff(data []byte) string {
	text := strings.ToValidUTF8(string(data), "\uFFFD")
	var rendered strings.Builder
	for _, line := range strings.SplitAfter(text, "\n") {
		trimmed := strings.TrimSuffix(line, "\n")
		if strings.HasPrefix(trimmed, "index ") || trimmed == `\ No newline at end of file` {
			continue
		}
		rendered.WriteString(line)
	}
	if rendered.Len() > 0 && !strings.HasSuffix(rendered.String(), "\n") {
		rendered.WriteByte('\n')
	}
	return rendered.String()
}

func readWorkspaceEntry(path string) ([]byte, string, error) {
	info, err := os.Lstat(path)
	if err != nil {
		return nil, "", err
	}
	if info.Mode()&os.ModeSymlink != 0 {
		target, err := os.Readlink(path)
		return []byte(target), "120000", err
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, "", err
	}
	mode := "100644"
	if runtime.GOOS != "windows" && info.Mode().Perm()&0o111 != 0 {
		mode = "100755"
	}
	return data, mode, nil
}

func removeWorkspaceDiff(root string) error {
	path := filepath.Join(root, WorkspaceDiffFilename)
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove memory workspace diff file %s: %w", path, err)
	}
	return nil
}

func appendBoundedWorkspaceDiff(rendered *strings.Builder, diff string) {
	if len(diff) <= WorkspaceDiffMaxBytes {
		rendered.WriteString(diff)
		if !strings.HasSuffix(diff, "\n") {
			rendered.WriteByte('\n')
		}
		return
	}
	boundary := WorkspaceDiffMaxBytes
	for boundary > 0 && !isUTF8Boundary(diff, boundary) {
		boundary--
	}
	rendered.WriteString(diff[:boundary])
	if !strings.HasSuffix(rendered.String(), "\n") {
		rendered.WriteByte('\n')
	}
	fmt.Fprintf(rendered, "\n[workspace diff truncated at %d bytes]\n", WorkspaceDiffMaxBytes)
}

func isUTF8Boundary(value string, index int) bool {
	return index == 0 || index == len(value) || value[index]&0xc0 != 0x80
}

func splitNUL(data []byte) [][]byte {
	parts := bytes.Split(data, []byte{0})
	if len(parts) > 0 && len(parts[len(parts)-1]) == 0 {
		parts = parts[:len(parts)-1]
	}
	return parts
}

func runBaselineGit(ctx context.Context, root string, args ...string) ([]byte, error) {
	command := exec.CommandContext(ctx, "git", append([]string{"-c", "core.hooksPath=.codex-disabled-hooks"}, args...)...)
	command.Dir = root
	command.Env = append(os.Environ(), "LC_ALL=C", "LANG=C", "GIT_TERMINAL_PROMPT=0")
	output, err := command.CombinedOutput()
	if err != nil {
		if errors.Is(ctx.Err(), context.Canceled) || errors.Is(ctx.Err(), context.DeadlineExceeded) {
			return nil, ctx.Err()
		}
		return nil, fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(string(output)))
	}
	return output, nil
}
