package memories

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWorkspaceBaselineReportsAddedModifiedDeletedAndResets(t *testing.T) {
	ctx := context.Background()
	root := filepath.Join(t.TempDir(), "memories")
	if err := os.MkdirAll(filepath.Join(root, "rollout_summaries"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, MemoryFilename), []byte("old"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".gitignore"), []byte(".ignored\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	deleted := filepath.Join(root, "rollout_summaries", "deleted.md")
	if err := os.WriteFile(deleted, []byte("important stale evidence\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := PrepareWorkspace(ctx, root); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, MemoryFilename), []byte("new"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, MemorySummaryFilename), []byte("v1\nsummary"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ".ignored"), []byte("ignored-but-tracked"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(deleted); err != nil {
		t.Fatal(err)
	}
	diff, err := WorkspaceDiff(ctx, root)
	if err != nil {
		t.Fatal(err)
	}
	want := []GitBaselineChange{
		{Status: GitBaselineAdded, Path: ".ignored"},
		{Status: GitBaselineModified, Path: MemoryFilename},
		{Status: GitBaselineAdded, Path: MemorySummaryFilename},
		{Status: GitBaselineDeleted, Path: "rollout_summaries/deleted.md"},
	}
	if len(diff.Changes) != len(want) {
		t.Fatalf("changes = %+v", diff.Changes)
	}
	for index := range want {
		if diff.Changes[index] != want[index] {
			t.Fatalf("change %d = %+v, want %+v", index, diff.Changes[index], want[index])
		}
	}
	for _, fragment := range []string{
		"diff --git a/MEMORY.md b/MEMORY.md", "-old", "+new",
		"new file mode 100644", "+v1", "deleted file mode 100644", "-important stale evidence",
	} {
		if !strings.Contains(diff.UnifiedDiff, fragment) {
			t.Fatalf("unified diff missing %q:\n%s", fragment, diff.UnifiedDiff)
		}
	}
	if err := WriteWorkspaceDiff(root, diff); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, WorkspaceDiffFilename)); err != nil {
		t.Fatal(err)
	}
	if err := ResetWorkspaceBaseline(ctx, root); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, WorkspaceDiffFilename)); !os.IsNotExist(err) {
		t.Fatalf("workspace diff survived reset: %v", err)
	}
	clean, err := WorkspaceDiff(ctx, root)
	if err != nil || clean.HasChanges() || clean.UnifiedDiff != "" {
		t.Fatalf("diff after reset = %+v, %v", clean, err)
	}
}

func TestPrepareWorkspaceRecoversUnusableGitDirectory(t *testing.T) {
	root := filepath.Join(t.TempDir(), "memories")
	if err := os.MkdirAll(filepath.Join(root, ".git"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, MemoryFilename), []byte("memory"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := PrepareWorkspace(context.Background(), root); err != nil {
		t.Fatal(err)
	}
	diff, err := WorkspaceDiff(context.Background(), root)
	if err != nil || diff.HasChanges() {
		t.Fatalf("recovered workspace diff = %+v, %v", diff, err)
	}
}

func TestRenderWorkspaceDiffBoundsUTF8AndNoChanges(t *testing.T) {
	if got := RenderWorkspaceDiff(GitBaselineDiff{}); got != "# Memory Workspace Diff\n\nGenerated by Codex before Phase 2 memory consolidation. Read this file first and do not edit it.\n\n## Status\n- none\n" {
		t.Fatalf("empty rendered diff = %q", got)
	}
	large := strings.Repeat("a", WorkspaceDiffMaxBytes-1) + "茅" + strings.Repeat("b", 128)
	rendered := RenderWorkspaceDiff(GitBaselineDiff{
		Changes:     []GitBaselineChange{{Status: GitBaselineModified, Path: MemoryFilename}},
		UnifiedDiff: large,
	})
	if !strings.Contains(rendered, "- M MEMORY.md") || !strings.Contains(rendered, "[workspace diff truncated at 4194304 bytes]") || !strings.HasSuffix(rendered, "```\n") {
		t.Fatalf("bounded rendered diff markers missing")
	}
	if strings.ToValidUTF8(rendered, "") != rendered {
		t.Fatal("rendered diff is not valid UTF-8")
	}
}

func TestValidateConsolidationArtifacts(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, MemoryFilename), []byte("memory"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, MemorySummaryFilename), []byte("outdated\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := ValidateConsolidationArtifacts(root); err == nil || !strings.Contains(err.Error(), "does not start with v1") {
		t.Fatalf("invalid summary error = %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, MemorySummaryFilename), []byte("v1\nsummary\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := ValidateConsolidationArtifacts(root); err != nil {
		t.Fatal(err)
	}
}
